syne-tune/syne-tune

README.md, docs/schedulers.md, docs/search_space.md, syne_tune/report.py
=> Correct naming in docs

setup.cfg
*Description of changes:* This change is required to registered the repo in pypi.
=> add missing setup.cfg

.github/workflows/python-app.yml, examples/launch_height_standalone_scheduler.py, examples/training_scripts/resnet_cifar10/resnet_cifar10.py, syne_tune/backend/simulator_backend/simulator_callback.py, syne_tune/optimizer/schedulers/ray_scheduler.py, syne_tune/optimizer/schedulers/searchers/__init__.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/__init__.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py, syne_tune/optimizer/schedulers/searchers/bore/__init__.py, syne_tune/optimizer/schedulers/searchers/constrained_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/report.py, syne_tune/tuner_callback.py, tst/remote_launcher/folder1/folder2/main.py, tst/test_random_seed.py, tst/test_status.py
*Description of changes:* Automatically checks the presence of unused import.
=> add import used check in flake8

tst/test_report.py
=> Removed legacy test, which failed non-deterministically

benchmarks/launch_benchmarks.py, benchmarks/launch_hpo.py, benchmarks/launch_utils.py, benchmarks/scheduler_factory.py, benchmarks/show_experiment_results.py
=> Fix imports in benchmarks (cudos to David)

blackbox_repository/conversion_scripts/recipes.py, blackbox_repository/conversion_scripts/scripts/nasbench201_import.py, examples/launch_simulated_benchmark.py
Script to download and convert original NASBench201 data into blackbox_repository format
=> add script to download and convert nb201 data

blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
=> fix dict keys

benchmarks/checkpoint.py, benchmarks/scheduler_factory.py, benchmarks/show_experiment_results.py, examples/launch_moasha_instance_tuning.py, examples/launch_plot_results.py, examples/training_scripts/pbt_example/pbt_example.py, syne_tune/backend/backend.py, syne_tune/backend/local_backend.py, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/simulator_backend/simulator_backend.py, syne_tune/backend/simulator_backend/simulator_callback.py, syne_tune/backend/trial_status.py, syne_tune/constants.py, syne_tune/experiments.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges_impl.py, syne_tune/remote/remote_launcher.py, syne_tune/report.py, syne_tune/tuner.py, syne_tune/tuner_callback.py, syne_tune/tuning_status.py, tst/backend/main_checkpoint.py, tst/backend/test_fetch_results.py, tst/backend/test_simulator_backend.py, tst/test_report.py
=> Fix renaming leftovers, remove unused report function

blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
=> use evaluation and training time to estimate runtime

blackbox_repository/tabulated_benchmark.py
=> Fix blackbox backend for remote launcher

benchmarks/scheduler_factory.py
=> Small bug fix

syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
=> Improved error message

blackbox_repository/conversion_scripts/scripts/fcnet_import.py
=> Fix bug in fcnet_import

benchmarks/benchmark_factory.py, benchmarks/definitions/distilbert_on_imdb.py, benchmarks/definitions/lstm_wikitext2.py, benchmarks/definitions/mlp_on_fashion_mnist.py, benchmarks/definitions/nasbench201.py, benchmarks/definitions/resnet_cifar10.py, examples/launch_fashionmnist.py, examples/launch_fashionmnist_costaware.py, examples/training_scripts/distilbert_on_imdb/distilbert_on_imdb.py, examples/training_scripts/lstm_wikitext2/lstm_wikitext2.py, examples/training_scripts/mlp_on_fashion_mnist/mlp_on_fashion_mnist.py, examples/training_scripts/resnet_cifar10/resnet_cifar10.py
=> Refactoring of benchmarks: Separation of meta-data from training code

syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/__init__.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/cross_validation.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/kernel_factory.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/schedulers/bayesopt/gpautograd/test_kernel.py
This is a simple kernel function for the approximate cross-validation optimization with MOBSTER. It is needed by the experiments of Max.
=> New kernel for approximate cross-validation by MOBSTER (multi-fidelity)

syne_tune/optimizer/schedulers/fifo.py, syne_tune/optimizer/schedulers/synchronous/hyperband.py, syne_tune/tuner.py
=> Make sure that synchronous schedulers are treated correctly in Tuner

benchmarks/launch_hpo.py, blackbox_repository/tabulated_benchmark.py, syne_tune/backend/simulator_backend/simulator_backend.py
=> Small fixes in CL launcher

syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/constrained_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/cost_aware_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/cost_aware_gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/searcher.py, tst/schedulers/bayesopt/test_checkpointing.py
Cleans up random seed management in searchers. This allows us to control random choices for paired comparisons and testing.
=> Clean up random seed management in searchers

requirements-gpsearchers.txt, requirements.txt, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
=> Support batch suggest in gp_fifo_searcher

benchmarks/launch_utils.py, syne_tune/optimizer/schedulers/fifo.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/gp_sync_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, syne_tune/optimizer/schedulers/synchronous/hyperband.py, tst/test_schedulers.py
=> Support for GP bayesopt in synchronous Hyperband

benchmarks/scheduler_factory.py
=> small fix to allow bayesopt searcher for synchronous HB

benchmarks/launch_utils.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gp_model.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py
=> Allow to switch off fantasizing

syne_tune/optimizer/schedulers/searchers/searcher_factory.py
=> Make statsmodels dependence conditional

README.md
Sorry, I forgot to link in the tutorial
=> Link to tutorial

syne_tune/tuner.py
*Description of changes:* currently the tuner stops as soon as the search space is exhausted. This change allows the tuner to stop when the running trials finish or when the stop condition is met.
=> Let trials finish when search space is exhausted.

examples/launch_bayesopt_constrained.py
We were missing a launch example for constrained BO
=> Launch example for constrained HPO

docs/tutorials/basics/scripts/launch_sagemaker_backend.py
Fixing a minor bug in `docs/tutorials/basics/scripts/launch_sagemaker_backend.py`.
=> Fixing a minor bug in launch_sagemaker_backend.py

syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
=> Fix batch suggest

benchmarks/launch_sample_searcher_states.py, benchmarks/launch_utils.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/freeze_thaw.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/gpiss_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/issm.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/posterior_state.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gpiss_model.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/backend/test_simulator_backend.py, tst/schedulers/bayesopt/test_expdecay_model.py, tst/schedulers/bayesopt/test_iss_model.py, tst/schedulers/test_hyperband.py
This is implementing fantasizing properly for GP additive models, and also changes how fantasizing is done when observations are used for every epoch. Includes several unit tests.
=> Fantasizing for Gaussian additive surrogate models

syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/sagemaker_backend/sagemaker_utils.py, syne_tune/report.py
*Description of changes:* fix SM backend when metric_names is None or when instance-type is local.
=> Two small fixes on Sagemaker backend

syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/freeze_thaw.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/issm.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/posterior_state.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gpiss_model.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/schedulers/bayesopt/test_expdecay_model.py
These issues were not caught, because the relevant unit test was commented out.
=> Before after test

README.md, examples/launch_rl_tuning.py, examples/training_scripts/rl_cartpole/requirements.txt, examples/training_scripts/rl_cartpole/train_cartpole.py
=> RL cartpole example.

syne_tune/optimizer/schedulers/median_stopping_rule.py, tst/schedulers/test_schedulers_api.py
*Description of changes:* add median stopping rule baseline from Golovin.
=> add median stopping rule

README.md
=> Fix mentions of launch_height_local

benchmarking/cli/launch_hpo.py
=> correct path

syne_tune/tuner_callback.py
Fixes a bug which can lead to wrong st_tuner_time values when using the RemoteLauncher
=> Fix bug setting st_tuner_time in results callback

benchmarking/definitions/definition_distilbert_on_imdb.py, benchmarking/definitions/definition_mlp_on_fashion_mnist.py, benchmarking/definitions/definition_resnet_cifar10.py, benchmarking/nursery/lstm_wikitext2/definition_lstm_wikitext2.py
=> fix paths to training scripts

syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/tuning_job_state.py, syne_tune/search_space.py, tst/schedulers/bayesopt/test_scaling.py
=> Equality comparison (useful for unit tests)

syne_tune/search_space.py, tst/test_searchspace.py
=> Fix bug reported by Alexandre Tkatchev

syne_tune/tuning_status.py
=> Change dollar cost display format

syne_tune/backend/sagemaker_backend/instance-types-cost.csv
=> Adding g5 Sagemaker instances

examples/launch_nas201_transfer_learning.py, syne_tune/optimizer/schedulers/transfer_learning/__init__.py, syne_tune/optimizer/schedulers/transfer_learning/bounding_box.py, tst/schedulers/test_schedulers_api.py
=> Fix gap between doc and actual dimensions of transfer learning tensors.

syne_tune/report.py
=> Only report cost on known instances.

syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
=> Better error message and comment

syne_tune/remote/remote_launcher.py
=> Typo in log message

README.md, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, tst/schedulers/bayesopt/test_hp_ranges.py
In case of warmstart (active search space specified) candidates from active search space should be sampled for random search.
This also adds few instructions on how to develop this library.
=> Sample from active space for warmstart for random search

syne_tune/optimizer/schedulers/searchers/utils/default_arguments.py
=> Don't print the last "\n"

syne_tune/tuner.py
=> Tuner._enrich_metadata should not overwrite field if already set

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/synchronous/hyperband_impl.py, tst/schedulers/test_schedulers_api.py
These short names would be useful for the paper, since I want to make a table for the schedulers
=> Add additional baselines

examples/launch_tuning_gluonts.py, examples/training_scripts/gluonts/train_gluonts.py
=> fix gluonts example

syne_tune/search_space.py, tst/test_searchspace.py
=> Fix to_dict, from_dict for Domain

benchmarking/nursery/lstm_wikitext2/lstm_wikitext2.py, benchmarking/training_scripts/distilbert_on_imdb/distilbert_on_imdb.py, benchmarking/training_scripts/mlp_on_fashion_mnist/mlp_on_fashion_mnist.py, benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py, docs/tutorials/basics/scripts/traincode_report_eachepoch.py, docs/tutorials/basics/scripts/traincode_report_end.py, docs/tutorials/basics/scripts/traincode_report_withcheckpointing.py, examples/training_scripts/checkpoint_example/checkpoint_example.py, examples/training_scripts/constrained_hpo/train_constrained_example.py, examples/training_scripts/constrained_hpo/train_fairhpo_tutorial.py, examples/training_scripts/cost_aware_hpo/train_cost_aware_example.py, examples/training_scripts/gluonts/train_gluonts.py, examples/training_scripts/height_example/train_height.py, examples/training_scripts/height_with_cost/train_height_with_cost.py, examples/training_scripts/mo_artificial/mo_artificial.py, examples/training_scripts/nasbench201/nasbench201.py, examples/training_scripts/pbt_example/pbt_example.py, examples/training_scripts/rl_cartpole/train_cartpole.py, syne_tune/__init__.py, tst/test_report.py, tst/trial_backend/main_checkpoint.py
*Description of changes:* This changes adds `Reporter` to root init allow easier user import.
=> Reporter in root __init__.py to ease user imports

syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/common.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges_impl.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/tuning_job_state.py
=> Robust equality operators in order to enable unit testing

benchmarking/nursery/benchmark_kdd/baselines.py, syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/transfer_learning/zero_shot.py
Temporarily changed BaseSearcher to accept **kwargs, otherwise it won't work with Mixin. Won't be needed as soon as config_space renaming happened.
=> Zero Shot Transfer HPO (SMFO)

benchmarking/blackbox_repository/conversion_scripts/recipes.py, benchmarking/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, benchmarking/blackbox_repository/conversion_scripts/scripts/lcbench/api.py, benchmarking/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py
*Description of changes:* add LCBench which contains 2K hyperparameters evaluated on 35 datasets
=> Add LCBench to blackbox repository

syne_tune/optimizer/schedulers/searchers/kde_searcher.py
=> allow for finite range parameter

benchmarking/nursery/benchmark_kdd/baselines.py, syne_tune/optimizer/schedulers/fifo.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/sgpt_model.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/transfer_learning/__init__.py
Added another transfer learning baseline: Scalable Gaussian Process Transfer
Problems:
- Init points by default are 3, should be 0.
- If we can set it to 0, requires special treatment of that case since the standard GP without data won't work
- Not sure, standard scaling actually works too well for this method. I saw the GPs for the target task predict very extreme values. Originally, it used normalizing targets to [0, 1].
=> Scalable Gaussian Process Transfer

benchmarking/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
=> remove token to enable downloading of the actual file

benchmarking/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
=> drop logging config

benchmarking/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, benchmarking/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py, benchmarking/cli/benchmark_factory.py, benchmarking/cli/launch_hpo.py, benchmarking/definitions/definition_lcbench.py, benchmarking/definitions/definition_nasbench201.py, benchmarking/definitions/definition_nashpobench.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/common.py
=> Included definition for LCBench and improve handling of datasets

syne_tune/optimizer/schedulers/synchronous/hyperband.py, syne_tune/optimizer/schedulers/synchronous/hyperband_bracket_manager.py
=> Fixed bug in sync HB

syne_tune/config_space.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges_impl.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/scaling.py, tst/schedulers/bayesopt/test_hp_ranges.py
=> Support reverse-log scaling as Domain

benchmarking/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, benchmarking/cli/scheduler_factory.py, benchmarking/definitions/definition_mlp_on_fashion_mnist.py, benchmarking/definitions/definition_nashpobench.py, syne_tune/optimizer/schedulers/hyperband.py, tst/schedulers/test_hyperband_cost_promotion.py
Needed in order to make cost-aware HPO work again
=> Fixes for cost-aware MOBSTER, and cost model for nashpobench

syne_tune/blackbox_repository/conversion_scripts/utils.py, syne_tune/blackbox_repository/repository.py
Try to upload preprocessed files to S3 but don't fail if it doesn't work.
=> Load Benchmarks without S3 Credentials

benchmarking/nursery/benchmark_automl/baselines.py
Add missing method to baselines file.
=> Add SMFO to AutoMLConf Benchmark

syne_tune/util.py
=> Fix SageMaker Root Path

syne_tune/tuning_status.py, tst/test_status.py
=> Compute Statistics for Numeric Results Only

tst/test_experiment_path.py
*Description of changes:* add test to make sure that experiment path is preserved under different scenarios (running locally, inside sagemaker, w/o local path etc).
=> test experiment path

syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges_impl.py, syne_tune/optimizer/schedulers/searchers/utils/warmstarting.py, tst/schedulers/bayesopt/test_hp_ranges.py
Also fixes issue with warmstarting and binary task attribute
=> HyperparameterRanges returns ranges of encoded representation

syne_tune/optimizer/schedulers/pbt.py
=> Minor comment change in PBT

container/Dockerfile, container/build_syne_tune_container.sh, syne_tune/optimizer/baselines.py, syne_tune/remote/remote_launcher.py
*Issue #, if available:* #243
*Description of changes:* Update remote launcher default image to use py38 and pytorch rather than mxnet (we use more pytorch than mxnet, it is a better default). also fix conditional import.
=> Update python version in remote launcher, fix conditional import

syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/bore/multi_fidelity_bore.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, tst/schedulers/test_schedulers_api.py
*Description of changes:* Implements an interface such that we can use BORE as model for Hyperband. This PR also adds some random sampling without replacement to BORE
=> implements interface to use BORE as model for Hyperband

benchmarking/nursery/benchmark_automl/baselines.py, benchmarking/nursery/benchmark_automl/results_analysis/show_results.py, benchmarking/nursery/benchmark_automl/results_analysis/utils.py
*Description of changes:* add bore to automl experiments
=> add bore to automl experiments

docs/faq.md
Fixed a small grammatical or typographical error in the FAQs.
=> Fixed typo/grammatical error

examples/launch_height_baselines.py, syne_tune/config_space.py, syne_tune/optimizer/schedulers/__init__.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/searchers/__init__.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, syne_tune/try_import.py
Fixes conditional imports, and some small changes required by our partner team
=> Small fixes and extensions. Also fixes conditional imports

benchmarking/nursery/tuning_with_hyperparameter_file/training_script.py, benchmarking/nursery/tuning_with_hyperparameter_file/tuning_example.py, docs/faq.md, requirements-gpsearchers.txt
=> Hyperparameters file

docs/search_space.md, syne_tune/config_space.py, syne_tune/optimizer/schedulers/searchers/bayesopt/datatypes/hp_ranges_impl.py, tst/schedulers/bayesopt/test_hp_ranges.py
Alternative to choice type, which can work better with model-based methods
=> Ordinal hyperparameter type (as opposed to categorical)

examples/launch_nasbench201_simulated.py, syne_tune/experiments.py, syne_tune/tuner_callback.py
=> small fixes on tensorboard callback

examples/launch_height_standalone_scheduler.py, syne_tune/optimizer/scheduler.py, syne_tune/optimizer/schedulers/median_stopping_rule.py, syne_tune/optimizer/schedulers/transfer_learning/bounding_box.py, tst/schedulers/test_schedulers_api.py
*Description of changes:* Fix an issue where the mode would not be displayed properly for some scheduler (the internal logic for find next configurations was not affected).
=> Fix mode MSR and HB+BB

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/bayesopt/utils/debug_log.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, tst/schedulers/test_grid_searcher.py, tst/schedulers/test_schedulers_api.py, tst/test_schedulers.py
*Issue #265 
*Description of changes: Adding GridSearcher and baseline for it (Unit test haven't included)
=> Grid search

syne_tune/blackbox_repository/repository.py
Blackbox generation was overlooked in the refactoring.
=> Fix Blackbox Generation

syne_tune/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
=> Fix NAS-Bench-201 Bug

syne_tune/tuner.py
There was a bug in the logic. Furthermore, disabled it by default.
=> Fix for wait_trial_completion

syne_tune/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py
Drop first and last epoch from the current LCBench version. Add further metrics.
=> LCBench Fix

requirements-aws.txt, requirements.txt, setup.py, syne_tune/__init__.py, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/trial_backend.py, syne_tune/blackbox_repository/blackbox_surrogate.py, syne_tune/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, syne_tune/blackbox_repository/conversion_scripts/utils.py, syne_tune/blackbox_repository/repository.py, syne_tune/experiments.py, syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/cost/sklearn_cost_model.py, syne_tune/try_import.py, syne_tune/tuner.py, syne_tune/tuner_callback.py, syne_tune/tuning_status.py, syne_tune/util.py
=> Remove AWS from core dependencies. Make sure local searchers still work

benchmarking/nursery/benchmark_automl/baselines.py, benchmarking/nursery/benchmark_automl/benchmark_main.py, syne_tune/backend/simulator_backend/simulator_backend.py
=> Fix for issue #323

benchmarking/nursery/remote_sm_backend/launch_experiment.py, benchmarking/nursery/remote_sm_backend/launch_remote.py
Working example of how to launch several SageMaker backend experiments in parallel
=> Example for remote launching of SageMaker backend experiments

benchmarking/nursery/benchmark_automl/benchmark_main.py, benchmarking/nursery/benchmark_dehb/baselines.py, benchmarking/nursery/benchmark_dehb/launch_remote.py
=> Fixes in benchmarking code

tst/schedulers/test_schedulers_api.py
=> add botorch

benchmarking/nursery/remote_sm_backend/launch_experiment.py, benchmarking/nursery/remote_sm_backend/launch_remote.py, benchmarking/nursery/remote_sm_backend/requirements.txt, syne_tune/backend/sagemaker_backend/sagemaker_utils.py
=> Extend SM backend example

README.md, examples/launch_height_standalone_scheduler.py, syne_tune/optimizer/baselines.py, syne_tune/optimizer/scheduler.py, syne_tune/optimizer/schedulers/fifo.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/neuralbands/neuralband_supplement.py, syne_tune/optimizer/schedulers/pbt.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py, syne_tune/optimizer/schedulers/searchers/kde/multi_fidelity_kde_searcher.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_callback.py, syne_tune/optimizer/schedulers/synchronous/dehb.py, syne_tune/optimizer/schedulers/synchronous/hyperband.py, syne_tune/optimizer/schedulers/synchronous/hyperband_impl.py, syne_tune/report.py, syne_tune/tuner.py, syne_tune/tuner_callback.py, tst/schedulers/bayesopt/test_expdecay_model.py
*Issue #, if available:* 355
- Replaces Dict -> dict in several files (cleanup)
- Fixes some docstrings
- Remove scheduler_mode (redundant)
=> Cleanup in preparation for developer tutorial

benchmarking/commons/launch_remote.py, benchmarking/nursery/benchmark_automl/benchmark_main.py, benchmarking/nursery/benchmark_hypertune/baselines.py, benchmarking/nursery/benchmark_hypertune/benchmark_definitions.py, benchmarking/nursery/benchmark_hypertune/benchmark_main.py, benchmarking/nursery/benchmark_hypertune/launch_remote.py, benchmarking/nursery/benchmark_hypertune/requirements.txt, syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gp_regression.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/__init__.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/posterior_state.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/utils.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/gpind_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/gpiss_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gp_model.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/hypertune/__init__.py, syne_tune/optimizer/schedulers/searchers/hypertune/hypertune_bracket_distribution.py, syne_tune/optimizer/schedulers/searchers/hypertune/hypertune_searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, syne_tune/optimizer/schedulers/searchers/utils/hp_ranges_impl.py, tst/schedulers/bayesopt/gpautograd/test_hypertune_ranking.py, tst/schedulers/test_schedulers_api.py, tst/test_schedulers.py
*Issue #, if available:* 327
This is the final PR, introducing all the new Hyper-Tune code
=> Implements Hyper-Tune and adds benchmark_hypertune

benchmarking/cli/scheduler_factory.py, examples/launch_height_ray.py, requirements-ray.txt, syne_tune/optimizer/schedulers/ray_scheduler.py, tst/schedulers/test_schedulers_api.py
=> update ray version

docs/tutorials/developer/README.md, docs/tutorials/developer/extend_async_hb.md, docs/tutorials/developer/extend_sync_hb.md, docs/tutorials/developer/first_example.md, docs/tutorials/developer/new_searcher.md, docs/tutorials/developer/random_search.md, docs/tutorials/developer/trial_scheduler_api.md
=> Developer tutorial: How to contribute a new scheduler

syne_tune/optimizer/schedulers/synchronous/dehb.py
=> Make DEHB use points_to_evaluate as well

README.md, docs/faq.md
I got this question one too many times. It is the most frequent question we get, so I put it at the top.
=> Extending FAQ

benchmarking/commons/launch_remote.py, benchmarking/nursery/fine_tuning_transformer_glue/launch_remote.py, benchmarking/nursery/remote_sm_backend/launch_experiment.py, examples/launch_tuning_gluonts.py
=> Switch off SageMaker debugger

docs/search_space.md, syne_tune/config_space.py, tst/schedulers/bayesopt/test_hp_ranges.py, tst/test_config_space.py
Follow-up for a change asked for by Martin, and also small fix to __repr__
=> Ordinal new2

syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/hyperband_promotion.py, syne_tune/optimizer/schedulers/hyperband_stopping.py, tst/schedulers/test_hyperband.py
=> Fixing bug in HyperbandScheduler

syne_tune/optimizer/schedulers/hyperband.py
*Issue #, if available:* 395
The problem was that if a training function does not implement checkpointing, it is started from scratch, and its reports before the resource it was resumed, need to be ignored. This was not done properly.
=> Fix for issue #395

syne_tune/optimizer/schedulers/searchers/searcher.py
Fixed the mid-point rule for the new ordinal types
=> Fix for imputation of points_to_evaluate for ordinal types

syne_tune/blackbox_repository/blackbox.py, tst/blackbox_repository/test_blackbox.py
*Description of changes:* checks that keys passed in input are in the search space.
=> Add check that keys passed in blackboxes are in the search space.

syne_tune/blackbox_repository/conversion_scripts/blackbox_recipe.py, syne_tune/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/icml2020_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py, syne_tune/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py, syne_tune/blackbox_repository/conversion_scripts/utils.py, syne_tune/blackbox_repository/repository.py
=> check hashes for bb files

syne_tune/backend/python_backend/python_backend.py, syne_tune/backend/python_backend/python_entrypoint.py, syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py, syne_tune/blackbox_repository/serialize.py, syne_tune/blackbox_repository/simulated_tabular_backend.py, syne_tune/config_space.py, syne_tune/tuner.py, tst/test_config_space.py
Simple helper function to convert a config space to dict and back.
=> Helper Function for Config Space Conversion

syne_tune/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/icml2020_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py, syne_tune/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py
Hash value matching fails right now. Remove for now until fixed.
=> Quickfix: remove hash checks

syne_tune/blackbox_repository/conversion_scripts/scripts/fcnet_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/icml2020_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py, syne_tune/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py, syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py, syne_tune/blackbox_repository/conversion_scripts/utils.py
Computes a logical hash for parquet files to avoid differences between machines
=> BB hashing fix

benchmarking/commons/hpo_main_simulator.py, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/blackbox_repository/simulated_tabular_backend.py
=> Bug fix and change to react to new checks in Blackbox

tst/test_schedulers.py, tst/util_test.py
=> Add back test_scheduler BO cases (but fast enough)

syne_tune/backend/local_backend.py, tst/schedulers/bayesopt/gpautograd/test_gp.py
*Description of changes:* we are currently using the root logger for the local backend which prevents user from controlling this log level.
=> Remove usage of root logging for local backend.

README.md, benchmarking/commons/utils.py, docs/faq.md, docs/tutorials/basics/basics_outlook.md, docs/tutorials/basics/basics_randomsearch.md, docs/tutorials/benchmarking/README.md, docs/tutorials/benchmarking/bm_contributing.md, docs/tutorials/benchmarking/bm_local.md, docs/tutorials/benchmarking/bm_sagemaker.md, docs/tutorials/benchmarking/bm_simulator.md
- New tutorial on benchmarking
- Inserted links to the tutorial into rest of docs
- Small code changes, in particular supporting more SageMaker frameworks
=> Tutorial on benchmarking

benchmarking/nursery/transformer_wikitext/data.py, benchmarking/nursery/transformer_wikitext/model.py, benchmarking/nursery/transformer_wikitext/training_script.py
Add transformer on wikitext 2 benchmark
=> Transformer benchmark

tst/schedulers/bayesopt/test_bayesopt_eipu.py
=> Fix unit test

benchmarking/commons/benchmark_definitions/transformer_wikitext2.py
=> Change defaults for transformer_wikitext2 benchmark

README.md
Did not create an issue.
Update of the intro paragraph.
Added section and table of HPO methods.
Added section and table of MO methods.
(Did not add the check-pointing info for now.)
=> Optimtable

docs/source/tutorials/developer/first_example.rst, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/cost/sklearn_cost_model.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, syne_tune/remote/remote_launcher.py
=> Fixing links in docs

benchmarking/commons/hpo_main_simulator.py, benchmarking/commons/utils.py, benchmarking/nursery/benchmark_yahpo/hpo_main.py
=> Fix bug in benchmarking

.github/workflows/check-code-examples.yml, syne_tune/optimizer/schedulers/searchers/bore/bore.py, tst/blackbox_repository/test_blackbox.py, tst/schedulers/test_schedulers_api.py, tst/test_pointstoevaluate.py
Commenting out tests which touch RayTuneScheduler (which currently is buggy). This is a problem in Ray Tune, not on our end.
=> Comment out all tests involving RayTuneScheduler

README.md, docs/source/getting_started.rst
=> typo fix: evalutionary => evolutionary

.github/workflows/check-code-examples.yml, examples/launch_bayesopt_constrained.py, examples/launch_height_moasha.py, examples/launch_height_python_backend.py, examples/launch_height_ray.py, examples/launch_height_standalone_scheduler.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
This is fixing `launch_bayesopt_constrained.py`, and also runs this one as part of the CI
=> Fix examples

examples/training_scripts/checkpoint_example/train_height_checkpoint.py, syne_tune/config_space.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/hyperband_cost_promotion.py, syne_tune/optimizer/schedulers/hyperband_stopping.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/posterior_state.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/utils.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/base.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/cross_validation.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/exponential_decay.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/cost/cost_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/cost_fifo_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/gpiss_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/meanstd_acqfunc_impl.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/base_classes.py, syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/cost_aware/cost_aware_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/cost_aware/cost_aware_gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/hypertune/hypertune_searcher.py, syne_tune/optimizer/schedulers/synchronous/dehb.py, syne_tune/optimizer/schedulers/synchronous/hyperband_impl.py
=> Fix :math:``...`` issue

docs/source/examples.rst, docs/source/tutorials/developer/extend_async_hb.rst
=> Fix links in docs

syne_tune/optimizer/schedulers/searchers/regularized_evolution.py
Mutate the child config instead of the parent config.
=> mutate child config

syne_tune/blackbox_repository/repository.py
*Issue #, if available:* 462, 476
=> Deactivate blackbox hash checking, until this is fixed

syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/bore/multi_fidelity_bore.py, syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py
=> Fix bug in MultiFidelityBore

tst/schedulers/test_initial_suggests.py
=> Make test run faster

.github/workflows/check-code-examples.yml, examples/launch_tuning_gluonts.py, examples/training_scripts/rl_cartpole/train_cartpole.py
=> Change launch_tuning_gluonts.py to run on SageMaker by default

CHANGELOG.md
=> CHANGELOG for new release

docs/source/index.rst
This is following up on a suggestion by Giovanni
=> What's New section in our hosted docs

README.md
add links to relevant blog posts
=> link to blog posts

syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/base.py, syne_tune/optimizer/schedulers/searchers/botorch/botorch_searcher.py, tst/schedulers/bayesopt/gpautograd/test_kernel.py, tst/test_config_space.py
=> Small refactoring to suppress warnings

syne_tune/backend/local_backend.py, syne_tune/backend/python_backend/python_backend.py, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/simulator_backend/simulator_backend.py, syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py, syne_tune/blackbox_repository/serialize.py, syne_tune/report.py, syne_tune/tuner.py, syne_tune/util.py
=> Unify JSON serialization of dict

benchmarking/commons/baselines.py, benchmarking/commons/hpo_main_simulator.py, benchmarking/commons/launch_remote_simulator.py, docs/source/examples.rst, docs/source/tutorials/benchmarking/bm_simulator.rst, examples/launch_lcbench_simulated.py, syne_tune/blackbox_repository/blackbox_tabular.py, syne_tune/optimizer/schedulers/pbt.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/common.py, syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/botorch/botorch_searcher.py, syne_tune/optimizer/schedulers/searchers/constrained/constrained_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/cost_aware/cost_aware_gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/cost_aware/cost_aware_gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/hypertune/hypertune_searcher.py, syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py, syne_tune/optimizer/schedulers/searchers/model_based_searcher.py, syne_tune/optimizer/schedulers/searchers/random_grid_searcher.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/searcher.py, tst/schedulers/bayesopt/test_bo_algorithm_components.py, tst/schedulers/test_searchers.py
*Issue #, if available:* 505
Supports to restrict schedulers to a fixed set of configuration, instead of all the configuration space.
=> Restrict configs

docs/source/tutorials/developer/random_search.rst, docs/source/tutorials/developer/wrap_code.rst, examples/launch_huggingface_classification.py, examples/launch_tuning_gluonts.py
=> Extension of documentation

examples/launch_huggingface_classification.py, examples/launch_tuning_gluonts.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/common.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
=> Fix bug related to restrict_configurations

syne_tune/report.py
Triggered by a question on syne-interest
=> Check on values reported: None should not be allowed

examples/launch_tensorboard_example.py
As is, the example might lead to confusions because no results are stored to disk. This adds the StoreResultsCallback as well to make sure that a results file is generated. 
=> Update Tensorboard Example

docs/source/examples.rst, docs/source/tutorials/pasha/pasha.rst, examples/launch_pasha_nasbench201.py
=> Small fixes

syne_tune/optimizer/schedulers/searchers/searcher.py
Adapts the BaseSearcher for multi-objective optimizers. Replaces #530
=> Adapt Base Searcher for MO

.github/workflows/end-to-end-tests.yml
=> run launch_pasha_nasbench201.py example

syne_tune/callbacks/tensorboard_callback.py
Add a flag that allows to toggle the logging of hyperparameters.
=> Flag to log hyperparameters

syne_tune/optimizer/schedulers/hyperband_pasha.py
Account for renaming of `max_t` to `_max_t`.
=> Fix for PASHA

benchmarking/commons/baselines.py, benchmarking/commons/default_baselines.py, benchmarking/commons/hpo_main_simulator.py, benchmarking/commons/launch_remote_simulator.py, benchmarking/nursery/benchmark_dehb/baselines.py, benchmarking/nursery/benchmark_hypertune/baselines.py, benchmarking/nursery/benchmark_neuralband/baselines.py, docs/source/tutorials/benchmarking/bm_simulator.rst, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/hyperband_stopping.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gluon_blocks_helpers.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/utils.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/base.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/cross_validation.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/exponential_decay.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/fabolas.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/freeze_thaw.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/product_kernel.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/range_kernel.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/freeze_thaw.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/model_params.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/mean.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/meanstd_acqfunc.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/meanstd_acqfunc_impl.py, syne_tune/optimizer/schedulers/searchers/gp_multifidelity_searcher.py
=> Updates to benchmarking and docs

docs/source/schedulers.rst, docs/source/tutorials/basics/basics_bayesopt.rst, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/range_kernel.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/warping.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/kernel_factory.py, syne_tune/optimizer/schedulers/searchers/bayesopt/utils/test_objects.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/schedulers/bayesopt/gpautograd/test_mcmc.py, tst/schedulers/bayesopt/gpautograd/test_warping.py, tst/schedulers/bayesopt/test_gp_components.py
This is refactoring and fixing input warping, also making it available as option. This a step towards HEBO.
The only real new code is `warping.py`, everything else is just boilerplate and changes, plus extra tests.
=> Refactor warping

examples/launch_height_baselines.py, examples/launch_height_ray.py, examples/launch_height_sagemaker.py, examples/launch_height_sagemaker_checkpoints.py, examples/launch_height_sagemaker_custom_image.py, examples/launch_height_sagemaker_remotely.py, examples/launch_height_standalone_scheduler.py, examples/launch_plot_results.py, examples/launch_tensorboard_example.py, syne_tune/optimizer/schedulers/searchers/random_grid_searcher.py, tst/schedulers/test_grid_searcher.py
- Fix bug in `launch_height_baselines.py`. Refactored all examples to avoid such bugs
- Small change in grid searcher, correct treatment of extreme case
=> fix: Refactor examples using train_height in order to avoid bugs like that in launch_height_baselines.py, and fix edge case in GridSearcher

CHANGELOG.md
=> chore: update release date of v0.4.0

docs/source/tutorials/developer/random_search.rst, docs/source/tutorials/developer/wrap_code.rst, syne_tune/blackbox_repository/blackbox_tabular.py, syne_tune/optimizer/schedulers/searchers/__init__.py, syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/botorch/botorch_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py, syne_tune/optimizer/schedulers/searchers/model_based_searcher.py, syne_tune/optimizer/schedulers/searchers/random_grid_searcher.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_base.py, syne_tune/optimizer/schedulers/transfer_learning/quantile_based/quantile_based_searcher.py, syne_tune/optimizer/schedulers/transfer_learning/zero_shot.py
Changes SearcherWithRandomSeed to StochasticSearcher to highlight that any randomized algorithm - algorithms that make randomized decisions internally - should derive from this class. 
=> refactor(searcher): Change SearcherWithRandomSeed to StochasticSearcher

.github/.codecov.yml, .github/workflows/unit-tests.yml, .gitignore, README.md, requirements-dev.txt, tst/schedulers/bayesopt/gpautograd/test_cholesky_factorization.py, tst/schedulers/bayesopt/gpautograd/test_gp.py, tst/schedulers/bayesopt/gpautograd/test_posterior_state.py, tst/schedulers/test_hyperband_sychronous.py
Track code coverage using the codecov service
----
=> chore(ci): add code coverage service

.github/.codecov.yml
Use non-blocking status checks, rather than enforcing coverage increases with each change. 
----
=> chore: use non-blocking status checks

docs/source/tutorials/basics/basics_backend.rst, syne_tune/constants.py, syne_tune/report.py, tst/test_report.py
=> refactor: Configure logging tag in Reporter

CONTRIBUTING.md, docs/source/index.rst, docs/source/tutorials/transfer_learning/transfer_learning.rst
=> docs: Tell contributors about docs

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/multi_objective_regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, tst/schedulers/test_schedulers_api.py
Adds a multi-objective version of regularized evolution.
----
=> feat: multi-objective REA

benchmarking/commons/benchmark_definitions/resnet_cifar10.py, benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py, benchmarking/training_scripts/transformer_wikitext2/training_script.py
Refactoring of 2 of our benchmark scripts, which makes it easier to understand them. I did this so I can show them in tutorials.
----
=> refactor: Cleanup of benchmark examples

benchmarking/commons/hpo_main_local.py, benchmarking/commons/hpo_main_simulator.py, syne_tune/util.py
=> fix: Small fix of new longer naming convention

syne_tune/blackbox_repository/simulated_tabular_backend.py
Small fix related to #584 
----
=> fix: Small __setstate__ fix

benchmarking/commons/hpo_main_local.py, benchmarking/commons/launch_remote_local.py, benchmarking/nursery/fine_tuning_transformer_glue/hpo_main.py, docs/source/faq.rst, syne_tune/backend/sagemaker_backend/sagemaker_utils.py, syne_tune/remote/remote_main.py, syne_tune/tuner.py
As noted by Aaron, the previous solution was not transparent and maybe incomplete.
----
=> fix: Further improvements to logic syncing checkpoints to S3 or not

benchmarking/commons/hpo_main_local.py, benchmarking/commons/hpo_main_sagemaker.py, benchmarking/commons/launch_remote_local.py, benchmarking/commons/launch_remote_sagemaker.py, docs/source/tutorials/benchmarking/bm_local.rst, docs/source/tutorials/benchmarking/bm_sagemaker.rst, docs/source/tutorials/benchmarking/bm_simulator.rst, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/sagemaker_backend/sagemaker_utils.py, syne_tune/callbacks/tensorboard_callback.py, syne_tune/constants.py, syne_tune/remote/remote_launcher.py, syne_tune/remote/remote_metrics_callback.py, syne_tune/tuner.py, syne_tune/tuner_callback.py
=> feature: Remote metrics

benchmarking/nursery/benchmark_warping/__init__.py, benchmarking/nursery/benchmark_warping/baselines.py, benchmarking/nursery/benchmark_warping/benchmark_definitions.py, benchmarking/nursery/benchmark_warping/hpo_main.py, benchmarking/nursery/benchmark_warping/launch_remote.py, benchmarking/nursery/benchmark_warping/requirements.txt, docs/source/schedulers.rst, docs/source/tutorials/basics/basics_bayesopt.rst, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/distribution.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gluon_blocks_helpers.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/gp_regression.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/gp_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/gpind_model.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/target_transform.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/schedulers/bayesopt/gpautograd/test_mcmc.py, tst/schedulers/bayesopt/gpautograd/test_target_transform.py
Next step towards HEBO. Allows for invertible target transform which can depend on a parameter. This parameter is learned together with all the others.
----
=> feature: Target transforms like Box-Cox (as in HEBO)

docs/source/tutorials/developer/first_example.rst, syne_tune/optimizer/scheduler.py
Closes #601   (along with PR #602)
----
=> Improve docs on SchedulerDecision

README.md, docs/source/getting_started.rst
Closes #627 
If a better way emerges for how to install from source, will re-open the issue and re-implement.
----
=> docs: update instructions for how to install from source

.github/workflows/end-to-end-tests.yml, benchmarking/nursery/test_checkpoints/__init__.py, benchmarking/nursery/test_checkpoints/baselines.py, benchmarking/nursery/test_checkpoints/hpo_main.py, benchmarking/nursery/test_checkpoints/launch_remote.py, benchmarking/nursery/test_checkpoints/requirements-synetune.txt, docs/source/examples.rst, docs/source/faq.rst, docs/source/tutorials/basics/basics_promotion.rst, docs/source/tutorials/multifidelity/mf_asha.rst, examples/launch_fashionmnist_checkpoint_removal.py, syne_tune/callbacks/hyperband_remove_checkpoints_callback.py, syne_tune/callbacks/hyperband_remove_checkpoints_score.py, syne_tune/optimizer/schedulers/hyperband.py, syne_tune/optimizer/schedulers/hyperband_checkpoint_removal.py, syne_tune/optimizer/schedulers/hyperband_promotion.py, syne_tune/optimizer/schedulers/hyperband_stopping.py, syne_tune/optimizer/schedulers/searchers/dyhpo/hyperband_dyhpo.py, syne_tune/util.py, tst/callbacks/test_hyperband_remove_checkpoints.py
Main PR on speculative checkpoint removal.
----
=> feat: Speculative early checkpoint removal for async multi-fidelity

docs/source/getting_started.rst
Our docs did not offer links to "what is HPO?".
----
=> docs: Link to D2L chapter in our docs

benchmarking/commons/utils.py
=> fix: Random seed range in benchmarking

tst/trial_backend/test_local_trial_backend.py
=> chore: Increase time limits on flakey tests

README.md, docs/source/getting_started.rst
add NSGA-2 to list of MO optimizers
----
=> docs: Update README.md

benchmarking/commons/utils.py
Replace recursive glob by normal glob
----
=> fix: Bugfix in benchmarking

benchmarking/training_scripts/lstm_wikitext2/lstm_wikitext2.py, benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py
Simplify a few things, since I am using this in the tutorial.
----
=> refactor: Cleanup of training scripts

.github/workflows/check-standalone-bayesian-optimization.yml
Re-add `check-standalone-bayesian-optimization.yml` workflow
----
=> chore: re-introduce check-standalone-bayesian-optimization.yml

syne_tune/config_space.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, tst/schedulers/test_rea.py
=> fix: Domain.len returns 0 for infinite domain (e.g., Float)

docs/source/index.rst, docs/source/tutorials/benchmarking/bm_plotting.rst, docs/source/tutorials/benchmarking/bm_simulator.rst, docs/source/tutorials/visualization/README.rst, docs/source/tutorials/visualization/code/plot_learning_curves.py, docs/source/tutorials/visualization/code/plot_single_experiment_results.py, docs/source/tutorials/visualization/comparisons.rst, docs/source/tutorials/visualization/plot_per_trial.rst, docs/source/tutorials/visualization/single_experiment.rst, syne_tune/experiments/plotting.py
=> docs: Tutorial for plotting

benchmarking/commons/benchmark_definitions/finetune_transformer_glue.py, benchmarking/commons/hpo_main_local.py, benchmarking/commons/hpo_main_sagemaker.py, benchmarking/commons/hpo_main_simulator.py, benchmarking/examples/benchmark_hypertune/plot_results.py, benchmarking/examples/fine_tuning_transformer_glue/plot_results.py
* Adds plotting code to benchmark
* Changes max_wallclock_time default
* Fix import bug (nursery -> examples)
----
=> feat: Plotting code for fine_tuning_transformer_glue benchmark

examples/launch_contributed_surrogate_bo.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_estimator.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_predictor.py, syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/contributed_surrogate_searcher.py, syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/estimator.py, syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/predictor.py, syne_tune/optimizer/schedulers/searchers/sklearn/__init__.py, syne_tune/optimizer/schedulers/searchers/sklearn/sklearn_surrogate_searcher.py, tst/schedulers/bayesopt/test_sklearn_surrogate.py, tst/schedulers/test_schedulers_api.py, tst/util_test.py
Adding new searcher that uses contributed surrogate models.
This comes with a new test and an example showing how it can be done
----
=> feat: Adding new searcher that uses contributed surrogate models. 

docs/source/schedulers.rst, docs/source/tutorials/developer/first_example.rst, docs/source/tutorials/multifidelity/mf_async_model.rst, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/independent/likelihood.py, syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/base.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/kernel_factory.py, syne_tune/optimizer/schedulers/searchers/bayesopt/models/meanstd_acqfunc_impl.py, syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/base_classes.py, syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/utils/warmstarting.py
Apart from allowing the base GP kernel to be selected, this contains a number of doc fixes.
----
=> feat: Allow base kernel to be selected

benchmarking/commons/benchmark_definitions/transformer_wikitext2.py, benchmarking/training_scripts/transformer_wikitext2/training_script.py
Cleans up benchmarking code. This is because I'd like to show it in the tutorial
----
=> refactor: Clean up transformer_wikitext2 code

docs/source/tutorials/visualization/comparisons.rst, syne_tune/experiments/aggregate_results.py, syne_tune/experiments/plotting.py
If a setup has a single seed only, there is no aggregation and no error bars, but it still works.
----
=> feat: Plotting for single seed results works as well

examples/launch_ask_tell_scheduler.py
Just a small typo fix found while checking out the examples :) 
----
=> docs(examples): Typo fix

.github/workflows/end-to-end-tests.yml, examples/launch_height_sagemaker_remotely.py, syne_tune/backend/sagemaker_backend/sagemaker_backend.py, syne_tune/backend/simulator_backend/simulator_backend.py, syne_tune/experiments/experiment_result.py, syne_tune/optimizer/schedulers/median_stopping_rule.py, syne_tune/optimizer/schedulers/transfer_learning/bounding_box.py, syne_tune/optimizer/schedulers/transfer_learning/quantile_based/quantile_based_searcher.py, syne_tune/remote/remote_main.py
Fixes a bug (and adds test) which blocks one of our customers.
Apart from this, I also replaced `logging` with `logger` at several places.
Closes #716 
----
=> fix: Fix bug in RemoteLauncher with SageMakerBackend

.github/workflows/integ-tests.yml, examples/launch_asha_yahpo.py
Helps https://github.com/awslabs/syne-tune/issues/714
----
=> fix: Removed the broken example from github actions

.github/workflows/integ-tests.yml, syne_tune/blackbox_repository/conversion_scripts/scripts/requirements-yahpo.txt
Closes https://github.com/awslabs/syne-tune/issues/714 with the change proposed by @sumny (many thanks!)
----
=> chore: fix yahpo dependency version of configspace

benchmarking/commons/default_baselines.py, docs/source/getting_started.rst, examples/launch_mb_mo_optimization.py, syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/multiobjective/__init__.py, syne_tune/optimizer/schedulers/multiobjective/multi_surrogate_multi_objective_searcher.py, syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py, tst/schedulers/test_schedulers_api.py
I got a request on what we offer as multi-objective methods. It is really important for adoption that when we implement something new, we add wrappers and update the docs.
----
=> refactor: Wrappers for multi-objective methods

docs/source/index.rst, docs/source/tutorials/dev_bayesopt/README.rst, docs/source/tutorials/dev_bayesopt/bo_components.rst, docs/source/tutorials/dev_bayesopt/gp_model.rst, docs/source/tutorials/dev_bayesopt/overview_structure.rst, docs/source/tutorials/dev_bayesopt/surrogate_model.rst, syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_model.py
This is the advanced developer tutorial on Bayesian optimization.
Please do give me feedback, also if something basic is missing (note there is another basic dev tutorial as well).
----
=> docs: New tutorial on how to implement Bayesian optimization

README.md
> REPLACE THIS TEXT BLOCK
>
> Describe the reason for this change, what the solution is, and any
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] for any code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/awslabs/syne-tune/blob/main/CONTRIBUTING.md
Closes #<issue number here>.
----
=> docs: Add CQR in list of method supported in readme

.github/workflows/run-syne-tune.yml, README.md, docs/source/getting_started.rst, requirements-dev.txt
1. Update README
2. Add `wheel` package to dev requirements, rather than a stand-alone entry in the README
----
=> chore: update README

syne_tune/optimizer/baselines.py
Pass additional arguments to searcher. Replaces #754
Closes #753 
----
=> fix: pass arguments to scheduler

syne_tune/backend/sagemaker_backend/sagemaker_backend.py
Newer version of SageMaker Estimator added a field which is not serializable, removing it.
Should fix integration tests issues https://github.com/awslabs/syne-tune/actions/runs/6704556262.
----
=> fix: Fix sagemaker backend

docs/source/index.rst, tst/schedulers/test_schedulers_api.py
Adds a link to Andreas AutoML seminar talk video.
Note the test fail for reasons dealt with in #807 and #806, so let us merge them first.
----
=> docs: Links to Andreas Mueller's talk on Mothernet

examples/training_scripts/rl_cartpole/requirements.txt, examples/training_scripts/rl_cartpole/train_cartpole.py
Update Ray to version `2.9.1` in the Cartpole example.
Closes #811 
----
=> chore: update Ray version in example

syne_tune/tuner.py
> REPLACE THIS TEXT BLOCK
>
> Describe the reason for this change, what the solution is, and any
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] for any code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/awslabs/syne-tune/blob/main/CONTRIBUTING.md
Closes #<issue number here>.
----
=> chore: typo

README.md
add link to discord channel
----
=> docs: add link to discord

syne_tune/blackbox_repository/blackbox_offline.py, syne_tune/blackbox_repository/conversion_scripts/scripts/requirements-yahpo.txt
Relax version requirements since fix in yahpo was merged.
----
=> update yahpo requirements, fix install on mac m cpus

benchmarking/nursery/visualize_plotly/interactive_plots.py
remove some redundant data loading in plotting script.
Closes #871 
----
=> fix: remove redundant code

benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py
=> fix: return error instead of acc

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/multiobjective/legacy_multi_objective_regularized_evolution.py, syne_tune/optimizer/schedulers/multiobjective/multi_objective_regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/legacy_regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, tst/schedulers/test_points_to_evaluate.py, tst/schedulers/test_rea.py, tst/schedulers/test_schedulers_api.py
replaces #885 
issue: #879 
----
=> refactor: REA and MO-REA

syne_tune/optimizer/schedulers/multiobjective/multi_objective_regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/bore/bore.py, syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py, syne_tune/optimizer/schedulers/searchers/regularized_evolution.py, syne_tune/optimizer/schedulers/searchers/searcher.py, syne_tune/optimizer/schedulers/searchers/single_objective_searcher.py, syne_tune/optimizer/schedulers/single_fidelity_scheduler.py, tst/schedulers/test_rea.py
Make single fidelity methods use `on_trial_complete` 
----
=> fix: use trial_complete

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/botorch/__init__.py, syne_tune/optimizer/schedulers/searchers/botorch/botorch_searcher.py, syne_tune/optimizer/schedulers/searchers/botorch/botorch_transfer_searcher.py, syne_tune/optimizer/schedulers/searchers/botorch/legacy_botorch_searcher.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, tst/schedulers/test_points_to_evaluate.py, tst/schedulers/test_schedulers_api.py
=> feat: refactor botorch searcher

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/searchers/conformal/legacy_surrogate_searcher.py, syne_tune/optimizer/schedulers/searchers/conformal/surrogate_searcher.py, syne_tune/optimizer/schedulers/searchers/legacy_searcher_factory.py, syne_tune/optimizer/schedulers/searchers/searcher_factory.py, tst/schedulers/test_legacy_schedulers_api.py, tst/schedulers/test_schedulers_api.py
refactors CQR searcher #879 
----
=> refactor: cqr

syne_tune/optimizer/schedulers/asha.py, syne_tune/optimizer/schedulers/searchers/random_searcher.py, tst/schedulers/test_schedulers_api.py
This PR makes ASHA runnable by:
- adds a few missing functionalities required by Tuner
- computes ranks correctly
- modifies random search such that we can combine it with ASHA
- adds a unittest for ASHA
----
=> refactor: make random search compatible with asha

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/multiobjective/expected_hyper_volume_improvement.py, syne_tune/optimizer/schedulers/multiobjective/legacy_expected_hyper_volume_improvement.py, tst/schedulers/test_schedulers_api.py
refactors ehvi and deprecates old version. #879 
----
=> refactor: ehvi

syne_tune/blackbox_repository/conversion_scripts/scripts/hpob_import.py, syne_tune/optimizer/schedulers/multiobjective/random_scalarization.py
HPO-B import script writes 1GB in `syne-tune` folder.
Also remote "\m" character which is not valid in python docstring.
=> fix: small fixes on hpo-b script

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/legacy_smac_scheduler.py
=> refactor: smac

syne_tune/optimizer/baselines.py, syne_tune/optimizer/schedulers/transfer_learning/legacy_zero_shot.py, syne_tune/optimizer/schedulers/transfer_learning/zero_shot.py, tst/schedulers/test_schedulers_api.py
=> refactor: zero shot

syne_tune/blackbox_repository/conversion_scripts/scripts/tabrepo_import.py
This PR makes changes to the tabrepo import script. It will now fill missing configurations with baseline values. Also refactored pre-processing to make it run faster.
----
=> fix: tabrepo import

benchmarking/baselines.py, benchmarking/benchmark_main.py, benchmarking/benchmarks.py, benchmarking/launch_slurmpilot.py, benchmarking/results_analysis/load_experiments_parallel.py, benchmarking/results_analysis/show_results.py
> REPLACE THIS TEXT BLOCK
>
> Describe the reason for this change, what the solution is, and any
> important design decisions you made. 
>
> Remember to follow the [CONTRIBUTING GUIDE] for any code you submit.
>
> [CONTRIBUTING GUIDE]: https://github.com/awslabs/syne-tune/blob/main/CONTRIBUTING.md
Closes #<issue number here>.
----
=> feat: Update benchmarking to support tabrepo

benchmarking/baselines.py
pass initial `points_to_evaluate` to the searcher.
----
=> fix: pass points_to_evaluate

benchmarking/benchmark_main.py
`benchmark_main.py` now correctly handles constant values in the configuration space.
----
=> fix: handle constant values in configuration space sampling

syne_tune/optimizer/baselines.py
- use correct scheduler for CQR
- pass `random_search` as searcher for ASHA
----
=> fix: small fixes to baselines.py

benchmarking/baselines.py, benchmarking/benchmarks.py
This PR adds hpob to the benchmarking suite.
----
=> feat: add hpob to benchmarking

syne_tune/optimizer/schedulers/searchers/last_value_multi_fidelity_searcher.py
=> fix: upper bound for sampling seeds

syne_tune/blackbox_repository/README.md, syne_tune/blackbox_repository/repository.py
=> fix: typos in docstring

syne_tune/blackbox_repository/README.md
Change a flag such that the output stays the same as in the previous examples for consistency.
----
=> fix: udpate example in Blackbox Repository README
