syne-tune/syne-tune

README.md
release.sh

*Description of changes:* This updates install instructions now now that the library is registered in pypi. Also:
* fixes some remaining naming issues
* put all installation instructions at the begining of the How to run on SageMaker section

Doc: install instructions, move setup in How to run on SM upfront

---

syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/remote/remote_launcher.py
syne_tune/remote/remote_main.py

Default AWS region can be specified in the AWS CLI config (`~/.aws/config`) in addition to environment variables. `boto3.Session()` provides an interface to both.

Allow default region to be configured in the AWS CLI in addition to AWS_DEFAULT_REGION

---

syne_tune/remote/remote_launcher.py
syne_tune/remote/remote_main.py

Simplifying the remote launcher code as suggested in the [previous PR](https://github.com/awslabs/syne-tune/pull/54#discussion_r760158592).

Refactor remote launcher to remove the `region_name` argument

---

examples/launch_simulated_benchmark.py
syne_tune/backend/local_backend.py
syne_tune/remote/remote_launcher.py
syne_tune/remote/remote_main.py
syne_tune/tuner.py
syne_tune/util.py

Improves consistency of paths and information display to users. 
* we now display "results of trials will be saved on ..." on the remote machine rather than the local one
* change the remote tuner path to be consistent with the path used locally e.g. `{syne-tune-root}/{tuner-name}`.
* fix boolean handling of remote arguments and use the same approach for both flags
The behavior is unchanged when running locally and the same s3 paths are used with the remote launcher.

More consistent path in remote instances

---

benchmarks/launch_hpo.py
benchmarks/launch_utils.py
blackbox_repository/blackbox_tabular.py
blackbox_repository/tabulated_benchmark.py
blackbox_repository/utils.py
syne_tune/optimizer/schedulers/searchers/bayesopt/utils/debug_log.py

Allows seed for blackbox queries to be fixed, so that these queries become deterministic. This is needed if a blackbox is used for testing.

Allow to fix seed when querying blackbox

---

syne_tune/tuner.py
syne_tune/tuning_status.py
tst/test_status.py

*Description of changes:* Some users reported that having status report min/max of metrics depending on the mode is a bit counter-intuitive. This change makes the status report the last metric which is more intuitive, it also makes this explicit.
Before
```
Resource summary:
trial_id     status  iter  steps  width  height  step  mean_loss  epoch  worker-time
0  Completed   100    100     10       0     0   0.100000      1    10.189253
1  Completed   100    100     13      96     0   9.677101      1    10.188962
```
After
```
Resource summary (last result is reported):
trial_id     status  iter  steps  width  height  step  mean_loss  epoch  worker-time
0  Completed   100    100     10       0    99   0.100000    100    10.165935
1  Completed   100    100     13      96    99   9.677101 …
```

Report last metric in tuning statuses

---

examples/launch_plot_results.py
syne_tune/experiments.py
syne_tune/tuner.py

*Issue #87:*
*Description of changes:* enable doing `experiment.best_config()` as recommended in #87 . Also avoid accessing the tuner for plotting and getting best results.

Add best_config method, enrich metadata automatically generated.

---

syne_tune/backend/backend.py
syne_tune/backend/local_backend.py
syne_tune/tuner.py
tst/util_test.py

*Issue #115*
*Description of changes:* fix the issue of not setting sagemaker jobs uniquely. 
It works as intended on sagemaker backend. The small difference with #112 is that it also avoid having a path `{syne_tune_path}/{tuner_name}/{tuner_name}` when running with the local backend (e.g. it does not change how path are stored when running with local backend locally or remotely).

Fix path in sagemaker backend

---

syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/freeze_thaw.py
syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/issm.py
syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/likelihood.py
syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/learncurve/posterior_state.py

Code for sampling the unobserved part of a learning curve, given the observed part (and everything else). This is an important missing piece for simulation-based scoring. It is also useful to plot learning curve probabilistic predictions. Code for the ISS learning curve model was already present.

Joint posterior sampling for gp_expdecay models

---

.github/workflows/unit-tests.yml
README.md

Remove support for python 3.6 as it is end-of-life.

---

container/Dockerfile
container/README.md
container/build_syne_tune_container.sh

Genesis: I had troubles running a SM job that was successfully started when run from my local environment, but wouldn't get started through the RemoteLauncher. The reason was out-of-date version of `botocore` in the docker image.
Simply rebuilding the image didn't solve an issues, a `pip install --upgrade` flag had to be added. (This is because this out-of-date version of `botocore` comes with the base image, so without `--upgrade` other dependencies in the `requirements.txt` were downgraded from the most recent versions, rather than existing dependencies being updated.)
Additionally, the changes to `build_syne_tune_container.sh` allow to rebuild an image easily by simply rerunning the script (no need to first delete an image via `docker image rm`).
`README.md` …

Install the most recent python dependecies in the docker image

---

syne_tune/optimizer/scheduler.py
syne_tune/optimizer/schedulers/fifo.py
syne_tune/optimizer/schedulers/hyperband.py
syne_tune/optimizer/schedulers/synchronous/hyperband.py

Remove state_dict, load_state_dict from TrialScheduler

---

syne_tune/optimizer/schedulers/transfer_learning/__init__.py
syne_tune/optimizer/schedulers/transfer_learning/bounding_box.py

Replaces the TransferLearningScheduler in favor of a mixin. This will simplify implementing different types of transfer learning, e.g. transfer learning as part of a Hyperband RungSystem.

Replace TransferLearningScheduler with TransferLearningMixin

---

benchmarking/blackbox_repository/blackbox_offline.py
tst/blackbox_repository/test_blackbox.py

Allow BlackboxOffline _objective_function to return all fidelities when fidelity=None, since that's the API assumed by Blackbox.

Allow BlackboxOffline _objective_function to return all fidelities when fidelity=None

---

examples/training_scripts/gluonts/requirements.txt

*Description of changes:* we were using mainline before as callbacks were not in a published gluonts version.

use a fix version for gluonts example rather than mainline

---

syne_tune/tuner.py

Hello!
This patch handles the scenario when the trial is stopped externally, i.e. independently of the Scheduler, e.g. due to max_run argument (the timeout setting of the SM Estimator) or manually via the AWS console.
I encountered this issue when my individual trials had `max_run=10min`, and when they were stopped (by themselves), the `running_trials_ids` in `Tuner.run()` was not updated and hence the Tuner wouldn't start more trials.
The proposed solution is the best I could do at first glance, but there might be a more elegant way to handle this.
This logic of the proposed solution should be carefully reviewed by someone with a good understanding of the Tuner class, because I'm not 100% certain if it's fully consistent with other logic of this class.
By …

Tuner: handle the scenario when the trial is stopped externally, i.e. independently of the Scheduler

---

benchmarking/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py

s3_root param is missing in generate_lcbench

Fixed problem with LCBench

---

benchmarking/benchmark_loop/plot_results.py
benchmarking/blackbox_repository/blackbox_surrogate.py
benchmarking/blackbox_repository/blackbox_tabular.py
benchmarking/blackbox_repository/simulated_tabular_backend.py
syne_tune/backend/simulator_backend/simulator_callback.py
syne_tune/stopping_criterion.py

*Description of changes:* backport changes on blackboxes from kdd branch (I will open separate PR for CTS and additional tooling for experiment).
* add option to fit surrogate on subset
* standardize output before fitting surrogates
* make sure cumulative time is increasing in simulations
* change BlackboxRepositoryBackend surrogate parameters to string/dictionary and only fit estimator in a lazy fashion (as proposed in Matthias PR)

Blackbox surrogate dictionary, small fixes

---

.gitignore
syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/kernel/product_kernel.py
tst/schedulers/bayesopt/gpautograd/test_kernel.py

There is a typo in implementation of product kernel. This breaks warmstart functionality in some cases. 
This PR fixes typo and adds unit tests to check for correct functioning of the kernel.
----

Fix a typo in product kernel implementation, add / update kernel unit tests

---

benchmarking/nursery/lstm_wikitext2/definition_lstm_wikitext2.py
syne_tune/backend/local_backend.py
syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/backend/trial_backend.py

This unblocks tuning of HuggingFace models without syncing checkpoints to S3. If checkpoints are written locally to ~/, the local disk fills up quickly.
Supporting this for SageMaker backend will be a forthcoming PR. Already implemented it, but a test is missing.

Supporting deleting checkpoints once not needed anymore

---

benchmarking/blackbox_repository/simulated_tabular_backend.py
benchmarking/definitions/definition_nashpobench.py
syne_tune/tuner.py

One small fix. Also, I am changing the order of things done at the end of tuning, so that the callbacks are called first (this is where final results are stored -- this is most important to have), then the tuner model is saved, and finally all remaining trials are stopped. If the last one fails, we still have all the results.

Some small fixes

---

syne_tune/backend/sagemaker_backend/sagemaker_backend.py

There is bug in the s3-key convertion in sagemaker backend. S3-key contains a double slash. The conversion to python `Path` removes one of them. Consequently, the returned string is not a proper key anymore.
We should keep the s3 key as string and not convert it to `Path`. This pr fixes the issue.
```python
>>> from pathlib import Path
>>> str(Path("s3://xxx"))
's3:/xxx'
```

Fix s3-path

---

syne_tune/experiments.py

Metadata isn't read after downloading the file from s3, but is set to None. Downloading needs to happen before metadata is read. This PR fixes the issue.

Fix metadata remote

---

syne_tune/remote/remote_launcher.py

This PR extends the RemoteLauncher to accept custom user defined images. This gives the user the flexibility to customize remote launches with LocalBackend. I would also propose to upgrade syne-tune default image to python 3.9 or 3.10. Current version is python 3.6 which is depreciated in many packages.

Extend RemoteLauncher to accept custom image

---

syne_tune/optimizer/schedulers/searchers/regularized_evolution.py

*Description of changes:* avoid sampling the same candidate when performing mutation, otherwise on finite domain, there is a chance of sampling the same candidate.

avoid sampling the same candidate with mutations in REA

---

syne_tune/optimizer/schedulers/fifo.py

*Description of changes:* Some searchers such as TPE and BORE require the mode as input, but it's not passed in the FIFO searcher factory.

passing mode to searcher

---

examples/training_scripts/gluonts/requirements.txt
examples/training_scripts/gluonts/train_gluonts.py

*Description of changes:* Bumping the GluonTS version to the latest 0.9.5 release in the example's requirements. I tested this locally. The 0.9.x release branch of GluonTS does not have breaking changes that are relevant to this example, and the latest 0.9.5 brought back support for Python 3.6 (which some still use).

Bump GluonTS version in example

---

syne_tune/tuner.py

*Description of changes:* An argument to the Tuner was added which allows to control how to deal with running trials when the stopping criterion is met.

Control Decision for Running Trials When Stopping Criterion is Met

---

syne_tune/tuner.py

*Description of changes:* this change revert to not wait trial completion when stopping condition is met as it is the standard behavior in other packages and may surprise users who gives a maximum budget in the stopping condition.

Revert wait_trial_completion_when_stopping to False

---

benchmarking/nursery/benchmark_automl/benchmark_definitions.py
benchmarking/nursery/benchmark_automl/benchmark_main.py
syne_tune/blackbox_repository/simulated_tabular_backend.py
tst/blackbox_repository/test_data_consistency.py

*Issue #, if available:* 319
This is fixing issue #319 . The solution is to use KNN with K=1, because that does not interpolate between different points in the table. Notably, all other options (XGBoost, RandomForest) fail with even worse errors (elapsed_time not increasing with resource).

Test blackboxes and fix LCBench surrogate issue

---

syne_tune/stopping_criterion.py
tst/test_plateau_stopper.py

#330 
*Description of changes:* Implements a stopping criterion that terminates the HPO process if the metric hasn't improved for N consecutive steps.

Plateau stopper

---

benchmarking/cli/estimator_factory.py
benchmarking/nursery/remote_sm_backend/launch_experiment.py
docs/faq.md
docs/tutorials/basics/scripts/launch_sagemaker_backend.py
examples/launch_height_sagemaker.py
examples/launch_height_sagemaker_custom_image.py
examples/launch_height_sagemaker_remotely.py
examples/launch_huggingface_classification.py
examples/launch_moasha_instance_tuning.py
examples/launch_tuning_gluonts.py
syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/backend/sagemaker_backend/sagemaker_utils.py
tst/remote_launcher/test_remote_launcher_path.py
tst/trial_backend/checkpoint_sagemaker/test_checkpoint_sagemaker.py

*Issue #, if available:* 339
Tested this by launching experiment with n_workers=32, nothing was throttled.

Avoid experiment abort due to throttling of SageMaker job launching

---

benchmarking/nursery/benchmark_automl/benchmark_main.py
benchmarking/nursery/benchmark_dehb/launch_remote.py
syne_tune/blackbox_repository/conversion_scripts/recipes.py
syne_tune/blackbox_repository/repository.py
syne_tune/blackbox_repository/simulated_tabular_backend.py
syne_tune/try_import.py

This allows to run simulation on blackboxes as if checkpoint was not supported.
Also, it allows to run blackbox repository without having Yahpo installed (a message is printed out).

Support no checkpointing in BlackboxRepositoryBackend

---

benchmarking/commons/benchmark_main.py
benchmarking/commons/launch_remote.py
syne_tune/tuner.py

Can save substantial amount of disk space for large experiments with many repetitions and cases

Make saving Tuner object at end of tuning optional (default is to save)

---

syne_tune/optimizer/schedulers/botorch/botorch_searcher.py

*Description of changes:* The acquisition function used in Botorch `qExpectedImprovement` does not consider the parameter `maximize`. This fixes it by always casting to maximization problems as expected by this acquisition function. With this change, botorch becomes very competitive with other searchers.

Fix mode in Botorch searcher when maximizing.

---

benchmarking/commons/launch_remote.py
benchmarking/nursery/fine_tuning_transformer_glue/launch_remote.py
benchmarking/nursery/remote_sm_backend/launch_remote.py
syne_tune/experiments.py
syne_tune/remote/remote_launcher.py
syne_tune/util.py

This is fixing an annoying issue. When setting checkpoint_s3_uri = s3_experiment_path(...), if this does not end on "/", the SM training job will sync back anything from S3 with that prefix (without the "/").
For example, if checkpoint_s3_uri = ".../ASHA-1", it will sync back anything in ".../ASHA-1*", which includes ASHA-10, ASHA-11, ASHA-12, ... This is what happened to me just now.
Having checkpoint_s3_uri end on "/" fixes this. Note we also set the local directory to "/opt/ml/checkpoints/", so trailing "/".

Fixing issue with checkpoint_s3_uri usage (must end on "/")

---

benchmarking/nursery/visualize_plotly/interactive_plots.py
syne_tune/experiments.py

https://github.com/awslabs/syne-tune/issues/253
Added `plot_tuner_results` function with multiple options, but primarily displays the following interactive plot:

Add IPython util function to display results as parallel categories plot

---

syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/experiments.py

*Issue #, if available:* https://github.com/awslabs/syne-tune/issues/214
*Description of changes:* should fix the issue #214, as Matthias guessed some mismatch was occurring with prefixes when searching for trial information.

fix mismatch between trials in sagemaker backend.

---

benchmarking/commons/baselines.py
benchmarking/commons/benchmark_main.py
benchmarking/commons/launch_remote.py
benchmarking/nursery/benchmark_dehb/baselines.py
benchmarking/nursery/benchmark_hypertune/baselines.py
benchmarking/nursery/benchmark_neuralband/baselines.py
docs/search_space.md
syne_tune/config_space.py
syne_tune/optimizer/schedulers/searchers/utils/hp_ranges_impl.py
syne_tune/optimizer/schedulers/synchronous/hyperband_bracket.py
syne_tune/util.py
tst/schedulers/bayesopt/test_hp_ranges.py
tst/test_config_space.py

New encoding for ordinal, which does not weight the values equally. Change datatype of fcnet HP.

Support different kinds of ordinal type

---

syne_tune/optimizer/baselines.py
syne_tune/optimizer/schedulers/searchers/bore/bore.py

Small fix such that BORE actually evaluate all configs in `points_to_evaluate` before starting the search.

Make BORE evaluate pre-selected configurations first 

---

tst/test_tuner.py
tst/tuners/test_wait_trial_completion_when_stopping.py

*Issue #, if available:* https://github.com/awslabs/syne-tune/issues/392
*Description of changes:* Added a new test for the tuner to check whether the workers continue runnig with the flag on and are stopped with the flag off. Closes #392 

New test for wait_trial_completion_when_stopping param of Tuner

---

syne_tune/experiments.py

*Closes #251*
The warning has been corrected because the metric label is explicitly indicated; Display all metrics in an experiment relative to time.

Avoid Matplotlib Warning

---

syne_tune/tuner_callback.py

#410 #411 
Makes sure that `st_tuner_time` is in results dict, before reading it.

swap lines

---

benchmarking/training_scripts/lstm_wikitext2/lstm_wikitext2.py
benchmarking/training_scripts/mlp_on_fashion_mnist/mlp_on_fashion_mnist.py
benchmarking/training_scripts/resnet_cifar10/resnet_cifar10.py

Martin observed that if checkpoints are written after metrics are reported, the training job may get killed while writing the checkpoint.

Write checkpoint before reporting metrics in training loop

---

benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_sagemaker.py
benchmarking/commons/launch_remote_local.py
benchmarking/nursery/launch_sagemaker/baselines.py
syne_tune/backend/local_backend.py
syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/backend/simulator_backend/simulator_backend.py
syne_tune/backend/trial_backend.py
syne_tune/tuner.py
tst/trial_backend/test_local_trial_backend.py

*Issue #, if available:* 250
- Refactors SageMaker back-end to check how many workers are really busy before starting new ones. This is fixing issue #250 and also fixes inefficiencies with warm pooling. This new behaviour can be switched off, which means the Tuner goes over budget.
- Involves a tiny change in Tuner, namely that `_schedule_new_tasks` asks the backend how many workers are busy, instead of "trusting" `running_trials_ids`. The latter books trials as stopped or completed, even though they can still be busy. The old behaviour of Tuner is recovered by setting `start_jobs_without_delay=True`, but the default is set to False (because that fixes the issue and fixes inefficiencies in warm pooling
- There are possible use cases for …

Refactor backend

---

docs/source/examples.rst
docs/source/faq.rst
examples/launch_checkpoint_example.py
examples/training_scripts/xgboost/xgboost_checkpoint.py
syne_tune/backend/local_backend.py
syne_tune/experiments.py
syne_tune/tuner.py

*Issue #, if available:* https://github.com/awslabs/syne-tune/issues/422
*Description of changes:* Provides an example to retrieve the best checkpoint of a model after tuning. Also show log of trials to user when no metrics are emitted.

Add example showing how to retrieve a checkpoint from an xgboost model.

---

.github/workflows/check-standalone-bayesian-optimization.yml
syne_tune/backend/__init__.py
syne_tune/backend/local_backend.py
syne_tune/backend/sagemaker_backend/sagemaker_backend.py
syne_tune/backend/trial_backend.py
syne_tune/try_import.py

Previous checks were too wide. `LocalBackend` and `PythonBackend` work with core dependencies only, while `SageMakerBackend` just needs `aws`. None of them need `extra`.

Fix conditional dependencies for backends

---

benchmarking/commons/benchmark_definitions/yahpo.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_sagemaker.py
benchmarking/commons/launch_remote_simulator.py
syne_tune/blackbox_repository/conversion_scripts/scripts/yahpo_import.py

- Fix yahpo-nb301 benchmark: Shorten very long attribute names by removing common prefix
- Fix benchmarking tooling: Remote launching did not parse CL arguments properly

Fixes to yahpo_nb301 benchmark and to benchmarking tools

---

docs/source/examples.rst
examples/launch_ask_tell_scheduler.py
examples/launch_ask_tell_scheduler_hyperband.py
examples/launch_ask_tell_schedululer_hyperband.py

What: Setup an ask-tell interface like in scikit-optimize ([library](https://github.com/scikit-optimize/scikit-optimize), [issue that asks for it](https://github.com/scikit-optimize/scikit-optimize/issues/68) in scikit-opt) to enable users with very specific requirements to plug into the HPO engines implemented in syne-tune. This work would include providing an example that shows how to set up this mode of operation by calling a trial scheduler suggest and communicating results with on_trial_results.
Why: In order to use syne-tune at the moment, user needs to wrap their function evaluator into a script that can be executed by syne-tune. In some cases, experiments needed for function evaluations can be more complex and require extra orchestration (example vary …

Example usage of the ask-tell interface in syne-tune

---

benchmarking/commons/hpo_main_common.py
benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_sagemaker.py
benchmarking/commons/hpo_main_simulator.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_sagemaker.py
benchmarking/commons/launch_remote_simulator.py
benchmarking/commons/utils.py
docs/source/tutorials/benchmarking/bm_local.rst
docs/source/tutorials/benchmarking/bm_simulator.rst

Experiments which compare methods against each other, should share the same "master random seed", to which the repetition seed (0, 1, ...) is added. The current code just uses the repetition seed.
This is a problem of low entropy. Also, we want to pull together "real benchmark" data into new surrogate blackboxes, so we need to use different random seeds.
On the other hand, when comparing methods against each other, the same random seed (per repetition) should be used, which reduces variance between them (this is called "paired comparison"). So, the same master random seed should be used across an experiment, at least for the same benchmark.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Management of random seeds in benchmarking

---

syne_tune/num_gpu.py

*Issue #, if available:* Fix https://github.com/awslabs/syne-tune/issues/85 
*Description of changes:* The number of gpus was incorrectly detected in cases where nvidia-smi fails. I was able to reproduce the error and that this patch fixes the issue.

fix number of gpu computation

---

syne_tune/optimizer/schedulers/searchers/botorch/botorch_searcher.py

Fixes #518 
Changing `max_attemps`from 0 to 1 fixes the problem.
*New output*
```python
--------------------
Resource summary (last result is reported):
trial_id     status  iter  steps  width  height  step  mean_loss  epoch  worker-time
0  Completed     5      5     10       0   4.0   2.000000    5.0     0.534248
1  Completed     5      5      4     -63   4.0  -2.453846    5.0     0.528401
2  Completed     5      5     10      18   4.0   3.800000    5.0     0.526259
3  Completed     5      5      0     -43   4.0   5.700000    5.0     0.524436
4  Completed     5      5     15     100   4.0  11.428571    5.0     0.524801
5  Completed     5      5     16    -100   4.0  -8.648649    5.0     0.523618
6 InProgress     3      5      9     100   2.0  13.571429    3.0 …
```

Fix so BoTorch scheduler is able to fit gp model.

---

examples/training_scripts/rl_cartpole/requirements.txt

Problem: `examples/launch_rl_tuning.py` started failing, see for example https://github.com/awslabs/syne-tune/actions/runs/4108215352/jobs/7088647693#step:7:1
Solution: lock to specific dependency versions

lock dependency versions to fix `launch_rl_tuning.py` example

---

.github/workflows/end-to-end-tests.yml

**Problem:** e2e tests are getting triggered too frequently, such that there are often multiple instances running in parallel. And the e2e tests are not designed to handle concurrent runs. Concurrent runs are also more expensive.
**Solution:** don't run the e2e tests with every push, instead, only run manually before release. In a future PR, I'll improve the automation that we use so that the e2e tests are automatically invoked before each new release.

Don't run End-to-end tests with every push to `main`

---

benchmarking/commons/benchmark_definitions/yahpo.py
benchmarking/commons/hpo_main_common.py
benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_sagemaker.py
benchmarking/commons/hpo_main_simulator.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_simulator.py
benchmarking/nursery/launch_local/hpo_main.py
benchmarking/nursery/launch_local/launch_remote.py
benchmarking/nursery/launch_sagemaker/hpo_main.py
benchmarking/nursery/launch_sagemaker/launch_remote.py
docs/source/tutorials/benchmarking/bm_simulator.rst

- Increase max_wallclock_time for NB301 benchmark
- parse_known_args -> parse_args (this flags misspelled args)
- scale_max_wallclock_time argument
- main_hpo_sagemaker: warm_pool on by default
- Fix in launch_local, launch_sagemaker
- Output link to docs in commandparser

Some changes in benchmarking

---

.github/pull_request_template.md
CONTRIBUTING.md

Update contribution guidelines and PR template.
Adapted from the contribution guidelines and PR template used by the AWS CDK:
* https://github.com/aws/aws-cdk/blob/main/CONTRIBUTING.md
* https://github.com/aws/aws-cdk/blob/main/.github/PULL_REQUEST_TEMPLATE.md

chore: update contribution guidelines and PR template

---

docs/source/examples.rst

The previous one is misleading for a lot of folks which are not very familiar with the library. They try out the code setting a small number of evaluations to see if it runs and this often leads to a failure because the number of configuration started is smaller than the number of workers.

Updated stopping criterion recommended for PASHA

---

syne_tune/blackbox_repository/conversion_scripts/scripts/yahpo_import.py
tst/blackbox_repository/test_comparison.py

Refactors the code for interfacing the Syne Tune configuration structure to the YAHPO configuration structure.  
- The active hyperparameters are now calculated and filtered for before the fidelity values are considered.
- Reduced hardcoding of values by introducing self._fidelity_multiplier.
Follow-up to #559
----

refactor: YAHPO _objective_function parsing

---

syne_tune/optimizer/schedulers/searchers/kde/kde_searcher.py
syne_tune/optimizer/schedulers/searchers/kde/multi_fidelity_kde_searcher.py
tst/schedulers/test_kde_searcher.py

Conditions in `KernelDensityEstimator` for whether KDE models can be fit are typically violated in `MultiFidelityKernelDensityEstimator`, so this did the same as ASHA. Here, I am changing the choice of `r_acq` to depend on the "can fit" decision
----

fix: Fix of BOHB and SyncBOHB

---

benchmarking/commons/hpo_main_common.py
benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_simulator.py
docs/source/tutorials/benchmarking/bm_local.rst
docs/source/tutorials/benchmarking/bm_sagemaker.rst
docs/source/tutorials/benchmarking/bm_simulator.rst

In the current code, benchmake name and seed are not contained in the directory name for the results, but just in metadata.json. A more descriptive filename makes it easier to pick out or remove specific results.
----

refactor: Use longer descriptive names for result directories

---

.github/.codecov.yml

Disable inline codecov comments
Following docs: https://docs.codecov.com/docs/github-checks
----

chore: disable codecov inline annotations

---

benchmarking/commons/benchmark_definitions/fcnet.py
benchmarking/commons/hpo_main_simulator.py
syne_tune/optimizer/schedulers/hyperband.py
syne_tune/optimizer/schedulers/hyperband_stopping.py
syne_tune/optimizer/schedulers/searchers/bayesopt/gpautograd/hypertune/gp_model.py
tst/schedulers/bayesopt/gpautograd/test_warping.py

Without this fix, benchmarking does not work properly for simulator backend.
Also some fixes of docstrings, and extended default `max_wallclock_time` for `fcnet` benchmark.
----

fix: Fixes to benchmarking with simulator backend

---

docs/source/benchmarking/benchmark_dehb.rst
docs/source/benchmarking/benchmark_hypertune.rst
docs/source/benchmarking/benchmark_yahpo.rst
docs/source/benchmarking/fine_tuning_transformer_glue.rst
docs/source/benchmarking/launch_local.rst
docs/source/benchmarking/launch_sagemaker.rst
docs/source/examples.rst
docs/source/faq.rst
docs/source/getting_started.rst
docs/source/training_scripts.rst
docs/source/tutorials/basics/basics_asha.rst
docs/source/tutorials/basics/basics_promotion.rst
docs/source/tutorials/basics/basics_randomsearch.rst
docs/source/tutorials/basics/basics_setup.rst
docs/source/tutorials/developer/wrap_code.rst
docs/source/tutorials/multifidelity/mf_setup.rst
docs/source/tutorials/transfer_learning/transfer_learning.rst
examples/launch_tensorboard_example.py

Robustifies showing code snippets in the docs. Since ranges are selected not based on line numbers, but on how they start and end, this is more robust to code changes.
----

refactor: Make all literalinclude in docs independent of line numbers

---

docs/source/conf.py
requirements-dev.txt

Theme still requires jQuery (https://github.com/readthedocs/sphinx_rtd_theme/issues/1253) but Sphinx already dropped it. Therefore, it is now added via extension.
----

Upgrade to Sphinx 6

---

syne_tune/optimizer/scheduler.py
syne_tune/tuner.py
tst/schedulers/test_schedulers_api.py

Moved scheduler metadata generation from Tuner to the scheduler. Now different schedulers can override this metod to provide their own metadata.
----

chore: Moved scheduler metadata generation

---

syne_tune/optimizer/schedulers/multiobjective/linear_scalarizer.py
tst/schedulers/multiobjective/test_simple_scalarizer.py
tst/schedulers/test_schedulers_api.py

Added a simple linear scalarization scheduler that combines multiple objectives into one using weighted mean and optimizes the resulting metric with any singe-objective FIFO optimizer.
----

feat: simple linear scalarization scheduler

---

.github/workflows/run-syne-tune.yml

Issue: https://github.com/pypa/pip/issues/11972
New version of pip `23.1` broke installation of the `examples` module.
----

fix: CI failing with `ModuleNotFoundError: No module named 'examples'` error

---

.github/workflows/python-publish.yml

We recently updated how the Syne Tune release process works. Now, we use Release Drafter to draft release notes. 
Upon creating our new release (`v0.5.0`), the [python-publish.yml](https://github.com/awslabs/syne-tune/blob/main/.github/workflows/python-publish.yml) GitHub Actions workflow failed to trigger. 
Use the `published` type instead of `created`. This is because the `created` type isn't triggered when the release is drafted by automation versus a human. Use the `published` type instead.
See also:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
- https://stackoverflow.com/a/61066906/1380805
----

fix: GitHub Actions not publishing Syne Tune to PyPI

---

.github/workflows/end-to-end-tests.yml

End-to-end tests are failing with the following error:
```
An error occurred (ThrottlingException) when calling the ListTrainingJobs operation (reached max retries: 2): Rate exceeded
Error: Process completed with exit code 254.
```
This is because the aws cli command is calling the API too quickly.
- Call the API more slowly, with an embedded 2-second sleep between paginated calls to avoid throttling. 
- Rewrite script in Python for readability. 
----

fix: Fix `ListTrainingJobs` throttling for E2E tests

---

benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_sagemaker.py
benchmarking/commons/hpo_main_simulator.py
benchmarking/nursery/benchmark_dehb/hpo_main.py
benchmarking/nursery/benchmark_dyhpo/hpo_main.py
benchmarking/nursery/benchmark_hypertune/hpo_main.py
benchmarking/nursery/benchmark_neuralband/hpo_main.py
docs/source/tutorials/benchmarking/bm_local.rst
docs/source/tutorials/benchmarking/bm_sagemaker.rst
docs/source/tutorials/benchmarking/bm_simulator.rst

This is mainly renaming `map_extra_args` to `map_method_args`, and also makes sure this mapping is executed just before the creation of the scheduler, which allows the mapping function to modify all arguments (for example, also the config space).
----

refactor: Changes to benchmarking formalism

---

.github/semantic.yml

Context: CI was failing for https://github.com/awslabs/syne-tune/pull/644, because the PR title followed the ConventionalCommits convention, but the *commit title itself* did not. The app by default requires that the PR title and at least one commit follows the convention. We do not actually need the commit itself to follow the convention, since when merging, GitHub will by default suggest that the PR title is used in the commit message. 
Fix: configure the app to only validate the PR title itself, to make it easier for people to start contributing to Syne Tune. 
----

chore: only validate PR titles; specify list of valid prefixes

---

benchmarking/nursery/fine_tuning_hugging_face/multiple_choice_on_swag.py
benchmarking/nursery/fine_tuning_hugging_face/run_hpo.py

Adds an example how to optimize hyperparameters for fine-tuning transformer models from the HuggingFace hub on the SWAG Q/A dataset. The example also shows how to visualize the optimization process. Future PR will extend this example to include more sophisticated techniques (e.g checkpointing) to accelerate the HPO process.
----

feat: add example to optimize hyperparams of HF models on SWAG

---

docs/source/tutorials/benchmarking/bm_simulator.rst

Points out alternative to `restrict_configurations`, namely to use 1-NN surrogates.
Closes #505 .
----

docs: Alternative of 1-NN surrogate to restrict_configurations

---

.github/workflows/end-to-end-tests.yml
.github/workflows/integ-tests.yml

Related to https://github.com/awslabs/syne-tune/pull/647. Runs two missing examples as tests.
----

chore: run two additional examples as tests

---

benchmarking/commons/launch_remote_common.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_sagemaker.py
benchmarking/commons/launch_remote_simulator.py
docs/source/tutorials/benchmarking/bm_local.rst
docs/source/tutorials/benchmarking/bm_sagemaker.rst
docs/source/tutorials/benchmarking/bm_simulator.rst

Simple change to allow a launch command to be re-run if it failed after having launched a number of jobs already.
Together with Jacek's forthcoming PR, this will improve remote launching for customers.
----

feat: Allow to skip initial jobs in remote launching

---

benchmarking/commons/default_baselines.py
benchmarking/nursery/benchmark_multiobjective/README.md
benchmarking/nursery/benchmark_multiobjective/__init__.py
benchmarking/nursery/benchmark_multiobjective/baselines.py
benchmarking/nursery/benchmark_multiobjective/benchmark_definitions.py
benchmarking/nursery/benchmark_multiobjective/hpo_main.py
benchmarking/nursery/benchmark_multiobjective/launch_remote.py
docs/source/tutorials/multifidelity/mf_setup.rst
tst/benchmarking/benchmark_commons/test_hpo_main_local.py
tst/schedulers/multiobjective/test_simple_scalarizer.py

Add initial multiobjective benchmarking logic. This is to support the ongoing development and evaluation of multiobjective methods in Syne Tune.
This is based on the approach taken in `benchmarking/examples/benchmark_dehb`, re-using existing logic where possible.
New unit test added.
----

chore: add initial multiobjective benchmarking logic

---

tst/benchmarking/benchmark_commons/test_hpo_main_local.py

Unit test started failing after https://github.com/awslabs/syne-tune/pull/672 was merged, which adds an assert about the config space for the MOREA method. The unit test was returning an invalid config space, which failed the assert. 
Have the mock blackbox return a specific config space. 
Alternative considered: we can actually remove the `mock_blackbox` entirely, but then the test would run for >1sec.
----

chore: fix unit test

---

syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_estimator.py
tst/schedulers/bayesopt/test_sklearn_surrogate.py

This replaces: https://github.com/awslabs/syne-tune/pull/677
The behaviour for `syne_tune.optimizer.schedulers.searchers.bayesopt.models.gp_model.GaussProcEstimator.fit_from_state` is 
If ``self.state.pending_evaluations`` is not empty, we proceed as follows:
* Compute posterior for state without pending evals
* Draw fantasy values for pending evals
* Recompute posterior (without fitting)
In the case of Sklearn Estimators we do not support fantasizing therefore the process should stop at step 1. The method can be later overriden if fantasizing is to be added.
----

fix: Sklearn estimator now fits the surrogate model without considering pending evaluations.

---

syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/base_classes.py
syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py

Made scoring function compatible with acquisition function interface. This should not change any functionalities of acquisition function but enable scoring function to be used in a broader context.
1. Moved the __init__ from acquisition function to scoring function.
2. Updated the __init__ of IndependentThompsonSampling accordingly
3. Defined new ScoringClassAndArgs input parameter type
----

fix: Made scoring function compatible with acquisition function interface

---

benchmarking/commons/launch_remote_common.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_sagemaker.py
benchmarking/commons/launch_remote_simulator.py
docs/source/tutorials/benchmarking/bm_local.rst
docs/source/tutorials/benchmarking/bm_sagemaker.rst
docs/source/tutorials/benchmarking/bm_simulator.rst

This reverts commit d5cf1ae8beca969e07f21c7fb4bce45842473c4f.
----

fix: Revert "feat: Allow to skip initial jobs in remote launching (#662)"

---

README.md

Fix the following typos in the example code in the Getting Started section from the README:
* `train_height_simple` expects parameter `--steps` but `launch_height_simple.py` defines `epochs` as HPO parameter only and not `steps` -> rename `steps` to `epochs` in `train_height_simple`
* in `launch_height_simple.py`: `entry_point` set to `train_height.py` which does not match the name `launch_height_simple.py` from the first comment in the previous code cell -> changed `entry_point` to `launch_height_simple.py`
----

fix: typos in "Getting started" code example

---

benchmarking/commons/hpo_main_common.py
benchmarking/commons/launch_remote_common.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_simulator.py
docs/source/tutorials/benchmarking/bm_simulator.rst
syne_tune/optimizer/schedulers/searchers/regularized_evolution.py
syne_tune/remote/scheduling.py
tst/benchmarking/benchmark_commons/test_hpo_main_local.py

I could not directly use your decorater. Maybe there is a better solution.
----

feat: Try again in remote launching when ResourceLimitExceeded is caught

---

.github/workflows/unit-tests.yml
README.md

Two small changes: 
1. Enable caching for unit tests, this should make them run faster. This setting is already enabled for our integ and end-to-end tests, see https://github.com/awslabs/syne-tune/blob/main/.github/workflows/run-syne-tune.yml#L51
2. Fix broken link in README
Before this change, duration of most recent 3 test runs: 12m 10s, 14m 55s, 19m 7s.
After this change: 8m 37s, 7m 54s, 7m 12s
Roughly 30% improvement. 
Confounding factors: 
1. Sometimes there's a delay until a machine is available to pick up the new job
2. If there's a cache-miss with a new library version, it will download it from the internet 
----

chore: enable caching for unit tests, fix README typo

---

docs/source/tutorials/visualization/code/plot_learning_curves.py
docs/source/tutorials/visualization/comparisons.rst
syne_tune/experiments/plot_per_trial.py
syne_tune/experiments/plotting.py

Extends plotting in two ways:
* In `TrialsOfExperimentResults`, can now plot single and multi fidelity methods in the same figure
* Can select the subfigures to be plotted. This is useful if you group into (say) 4 or 8 buckets, but then want to create a sequence of plots comparing pairs of these
This is stuff I needed for the ODSC tutorial, they are just coming in now
----

feat: Some extra plotting features

---

syne_tune/experiments/experiment_result.py

```from syne_tune.experiments import load_experiment``` triggers 
```
Multi Objective Optimization dependencies are not imported since dependencies are missing. You can install them with
pip install 'syne-tune[moo]'
or (for everything)
pip install 'syne-tune[extra]'
```
Moving the import will avoid that.

fix: Avoid MOO warning message

---

benchmarking/commons/hpo_main_local.py
benchmarking/commons/hpo_main_sagemaker.py
benchmarking/commons/launch_remote_local.py
benchmarking/commons/launch_remote_sagemaker.py

Command line arguments did not work. I also pulled together common CL args between local and sagemaker
----

fix: Command line arguments of benchmarking

---

.github/workflows/integ-tests.yml
README.md
docs/source/examples.rst
examples/launch_asha_yahpo.py
examples/launch_mb_mo_optimization.py
syne_tune/optimizer/schedulers/multiobjective/multi_surrogate_multi_objective_searcher.py
syne_tune/optimizer/schedulers/multiobjective/random_scalarization.py
syne_tune/optimizer/schedulers/searchers/bayesopt/models/model_transformer.py
syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_model.py
syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py
syne_tune/optimizer/schedulers/searchers/model_based_searcher.py
tst/schedulers/test_schedulers_api.py

Adding the Multi Surrogate Multi Objective Searcher to SyneTune. 
To make this happen, added a few small changes:
1. NoOptimization optimizer now does not setup itself, this is necessary to use the same optimizer for multiple metrics
2. If no estimator for INTERNAL_METRIC_NAME can be found, ModelBasedSearcher uses the debug log from a randomly selected one
3. _assert_same_keys check only if skip_optimization is not None. None is the default case where all is skipped.
4. target_metric is passed to SKLearnEstimatorWrapper to differentiate estimators
----

feat: Multi Surrogate Multi Objective Searcher

---

requirements-dev.txt

You could investigate more, but fact is our docs do not currently build on readthedocs, and downgrading sphinx to <7.0.0 solves that issue. This is what I found:
https://github.com/readthedocs/readthedocs.org/issues/10279
----

fix: Avoid sphinx 7.0.0, since the readthedocs build fails with that

---

syne_tune/experiments/experiment_result.py
tst/experiments/test_experiment_result.py

* In [ExperimentResult.best_config()](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/syne_tune/experiments/experiment_result.py#L181C26-L181C26) `metric_mode` is resolved by calling `_metric_name_mode`
* In [_metric_name_mode](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0b113f1067a2da92039a/syne_tune/experiments/experiment_result.py#L223-L225): in case `metric_mode` has a non-zero length it is replaced by `metric_mode[metric]`. In case `metric_mode` is a string (for example `min`) and not a list, it is replaced by the character in the string at position `metric`, with `metric` defaulting to `0`. In case of `metric_mode = "min"` it is replaced by `m`.
* back in [best_config](https://github.com/awslabs/syne-tune/blob/254ad0708703245e51da0 …

fix: ExperimentResult.best_config() always used max mode

---

README.md
docs/source/getting_started.rst
docs/source/index.rst

Updates the README.md. Also, I added a link to the PyData video from Martin. Once the ODSC talk video is online, this goes there as well.
----

docs: Updated documentation

---

README.md
benchmarking/benchmark_definitions/finetune_transformer_swag.py
benchmarking/training_scripts/mlp_on_fashion_mnist/mlp_on_fashion_mnist.py
docs/source/faq.rst
docs/source/search_space.rst
docs/source/tutorials/basics/basics_bayesopt.rst
docs/source/tutorials/benchmarking/bm_simulator.rst
syne_tune/util.py
syne_tune/utils/__init__.py
syne_tune/utils/convert_domain.py
tst/test_convert_domain.py

This is automating some best practices for choosing domains in ``config_space``. Particularly useful for people who come from other tools, like Optuna, where you don't have the finite numerical types we have.
Closes #380.
----

feat: Automatic streamlining of configuration space

---

examples/launch_smac_example.py
setup.py
syne_tune/blackbox_repository/conversion_scripts/scripts/requirements-yahpo.txt

chore: Add smac to possible install tag, fix comment in example

---

examples/launch_plot_results.py
syne_tune/experiments/experiment_result.py

This allows to plot trials value over time directly from `ExperimentResult`, running
```python
from syne_tune.experiments import load_experiment
exp = load_experiment("...")
exp.plot_trials_over_time()
```
gives this plot: 
Also adds example.
Closes #764 .
----

feat: Add util to plot trials over time from ExperimentResult

---

requirements-dev.txt

**Problem:** The `Run Jupyter Notebooks` GitHub Actions CI workflow is failing
**Solution:** The [traitlets](https://github.com/ipython/traitlets/releases/tag/v5.12.0) package was recently updated from `5.11.2` to `5.12.0` which broke the script. Temporarily pin to `traitlets<=5.11.2`. Opened issue: https://github.com/ipython/traitlets/issues/887
----

fix: pin traitlets version to fix notebook conversion script

---

docs/source/tutorials/multifidelity/mf_asha.rst
docs/source/tutorials/multifidelity/mf_async_model.rst
docs/source/tutorials/multifidelity/mf_sync_model.rst
docs/source/tutorials/multifidelity/mf_syncsh.rst
examples/launch_resume_tuning.py
syne_tune/experiments/util.py
syne_tune/optimizer/baselines.py
syne_tune/optimizer/schedulers/smac_scheduler.py
tst/experiments/test_metric_name_mode.py

Add links to API docs in tutorial, and adds links to docstrings in `baselines.py`
Closes #776.
----

docs: Adding links to API in tutorials

---

README.md
docs/source/schedulers.rst
docs/source/tutorials/dev_bayesopt/bo_components.rst
syne_tune/blackbox_repository/blackbox_surrogate.py
syne_tune/blackbox_repository/requirements.txt
syne_tune/optimizer/schedulers/searchers/bayesopt/models/acqfunc_factory.py
syne_tune/optimizer/schedulers/searchers/bayesopt/models/meanstd_acqfunc_impl.py
syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py
tst/schedulers/test_choose_acqfunc.py
tst/schedulers/test_schedulers_api.py

The user can choose the acquisition function now, both in normal GP-based BO and in MOBSTER.
I am also fixing some build issues, related to a name change in scikit-learn. There is also a problem with `pymoo`, which is why I disable a test.
Closes #805 .
----

feat: Allow the acquisition function to be chosen in GPFIFOSearcher

---

tst/remote_launcher/test_remote_launcher_path.py
tst/schedulers/test_schedulers_api.py

This is to close an issue. We currently do not execute unit tests which require SageMaker. We run code in `examples/` which uses SageMaker, but not tests.
Closes #476.
----

chore: Uncommented test which needs SageMaker. It is still commented out

---

examples/training_scripts/nasbench201/nasbench201.py
syne_tune/blackbox_repository/conversion_scripts/blackbox_recipe.py
syne_tune/blackbox_repository/conversion_scripts/generate_all_blackboxes.py
syne_tune/blackbox_repository/conversion_scripts/generate_and_upload_all_blackboxes.py
syne_tune/blackbox_repository/conversion_scripts/scripts/fcnet_import.py
syne_tune/blackbox_repository/conversion_scripts/scripts/icml2020_import.py
syne_tune/blackbox_repository/conversion_scripts/scripts/lcbench/lcbench.py
syne_tune/blackbox_repository/conversion_scripts/scripts/nasbench201_import.py
syne_tune/blackbox_repository/conversion_scripts/scripts/pd1_import.py
syne_tune/blackbox_repository/conversion_scripts/scripts/yahpo_import.py
syne_tune/blackbox_repository/conversion_scripts/utils.py
syne_tune/blackbox_repository/repository.py
syne_tune/blackbox_repository/requirements.txt

Because the options of HF hub are different than what was supported in BB repository, the options now looks a bit different but I did my best to maintain option parity when possible.
The hash is not needed anymore since HF hub supports it.
I have noted an issue with LCBench data as an error is thrown now with a pandas update. I have sent an email to the authors and hotfixed the blackbox import code so that it can run with newer pandas code.

Blackbox repository to use HuggingFace as storage backend instead of S3

---

examples/launch_ask_tell_scheduler.py
examples/launch_ask_tell_scheduler_hyperband.py

Adapts the example files for ask-tell interface to load Syne-Tune's ask-tell scheduler. 
----

fix: import syne-tune's ask-tell scheduler

---

syne_tune/optimizer/schedulers/asha.py
syne_tune/optimizer/schedulers/searchers/searcher.py
syne_tune/optimizer/schedulers/single_fidelity_scheduler.py

- removes some boilerplate from BaseSearcher
- consistent naming
- handle random seeds
----

refactor: simplify searcher interface

---

syne_tune/optimizer/schedulers/single_fidelity_scheduler.py
syne_tune/tuner.py

Makes the `SingleFidelityScheduler` compatible with `Tuner`, and allows to use `Tuner` both with new and legacy schedulers.
----

refactor: make SingleFidelityScheduler compatible with tuner

---

.github/workflows/run-notebooks.yml
.github/workflows/run-syne-tune.yml

Update to v4 actions:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
----

fix: update to v4 actions 

---

benchmarking/nursery/benchmark_automl/baselines.py
syne_tune/optimizer/schedulers/__init__.py
syne_tune/optimizer/schedulers/legacy_median_stopping_rule.py
syne_tune/optimizer/schedulers/median_stopping_rule.py
tst/schedulers/test_legacy_schedulers_api.py
tst/schedulers/test_schedulers_api.py
tst/test_median_stopping_rule.py

- Uses new scheduler interface for median stopping rule #879 
- Deprecates old scheduler
- Adds additional unit test
----

refactor: median stopping rule

---

syne_tune/optimizer/schedulers/searchers/conformal/surrogate_searcher.py

We shouldn't set a trial-id in the suggest function. Instead we record configs  in `on_trial_complete` / `on_trial_result` directly to avoid miss match. 
----

fix: trial id in surrogate searcher

---

syne_tune/optimizer/schedulers/asha.py
syne_tune/optimizer/schedulers/searchers/conformal/conformal_quantile_regression_searcher.py
syne_tune/optimizer/schedulers/searchers/last_value_multi_fidelity_searcher.py
syne_tune/optimizer/schedulers/searchers/searcher_factory.py

- Renames SurrogateSearcher to ConformalQuantileRegression for clarity; it now only supports single-fidelity optimization.
- Adds a new LastValueMultiFidelitySearcher, which takes any SingleObjectiveSearcher as input and fits a model using only the last observed value from each trial.
----

refactor: surrogate searcher

---

syne_tune/optimizer/scheduler.py
syne_tune/optimizer/schedulers/pbt.py
syne_tune/optimizer/schedulers/single_fidelity_scheduler.py
syne_tune/optimizer/schedulers/smac_scheduler.py

makes sure to pass the meta data inside all schedulers for plotting in `ExperimentResults`
----

fix: pass meta data in all scheduler

---

docs/source/tutorials/developer/new_searcher.rst
syne_tune/optimizer/schedulers/asha.py
syne_tune/optimizer/schedulers/searchers/last_value_multi_fidelity_searcher.py
syne_tune/optimizer/schedulers/searchers/legacy_searcher_factory.py
syne_tune/optimizer/schedulers/searchers/multi_fidelity_searcher.py
syne_tune/optimizer/schedulers/searchers/searcher_factory.py
tst/schedulers/test_multi_fidelity_searcher.py

Unified naming from `searcher_cls` ->`searcher` and `searcher_cls_dict `-> `searcher_dict`
Closes #941.
----

reformat: unify scheduler argument naming

---

README.md
syne_tune/optimizer/schedulers/searchers/last_value_multi_fidelity_searcher.py

Samples a different random seed every time a new BaseSearcher gets initialized to avoid resampling of random configurations.
----

fix: change seed for base searcher

---

benchmarking/results_analysis/show_results.py
examples/launch_hpob.py
syne_tune/blackbox_repository/conversion_scripts/scripts/hpob_import.py

This PR fixes the hpob_import.
Closes #949.
----

Fix: Fix hpob import
